import type { JsonObject } from "../../types/component.js";

const DEFAULT_FONT_FAMILY =
  '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif';

export const singleValueChartDefaultProps: JsonObject = {
  componentName: "SingleValueChart",
  name: "单值占比图",
  percentValue: 50.56,
  style: {
    position: "absolute",
    left: 400,
    top: 400,
    width: 232,
    height: 196,
    zIndex: 1,
  },
  rotate: 0,
  opacity: 1,
  backgroundColor: "transparent",
  entryAnimiation: {
    isShow: false,
    type: "",
  },
  chartData: {
    isPolling: false,
    sourceType: "constant",
    constant: {
      data: [{ 百分比: "50.56" }],
      originalData: [{ 百分比: "50.56" }],
      fieldList: [
        {
          fieldName: "百分比",
          fieldDisplayName: "百分比",
          fieldType: "DECIMAL",
        },
      ],
    },
    form: {
      formPermType: "All",
      formUuid: "",
      formName: "",
    },
    api: {
      headers: [],
      processFunction: "function handleResponse (response) { return response }",
      requestBody: "",
      requestParam: [],
      fieldList: [],
      apiUuid: "",
    },
    polling: 3,
    indicator: [
      {
        fieldName: "百分比",
        fieldDisplayName: "百分比",
        fieldType: "DECIMAL",
        fieldDataConfig: {
          chartDisplayName: "百分比",
          calculateType: "SUM",
          format: {
            numberFormat: "numerical",
            Millimeter: false,
            accuracy: 2,
            dataFix: {
              preFix: "",
              auFix: "",
            },
          },
        },
      },
    ],
    dimension: [],
  },
  animationSettings: {
    isOpenAnimation: true,
    duration: 1000,
  },
  TextStyle: {
    fontFamily: DEFAULT_FONT_FAMILY,
    color: "#00E5FF",
    fontSize: 48,
    fontWeight: "bold",
    fontStyle: "normal",
    letterSpacing: 0,
    offsetX: 0,
    offsetY: 0,
    fontSizeFraction: 24,
    fontSizeFractionDecimal: 1,
    suffix: "%",
    suffixStyle: "normal",
    suffixfontFamily: DEFAULT_FONT_FAMILY,
    suffixfontWeight: "normal",
    suffixfontStyle: "normal",
    suffixcolor: "#00E5FF",
    suffixletterSpacing: 0,
    suffixoffsetX: 0,
    suffixoffsetY: 0,
    textShadowColor: "rgba(0,0,0,0.5)",
    textShadowBlur: 4,
    textShadowOffsetX: 0,
    textShadowOffsetY: 0,
  },
  showTextisShow: true,
  decimalisShow: true,
  postfixisShow: true,
  textShadowisShow: true,
  ringColor: "linear-gradient(180deg, rgba(22,212,254,1) 0%, rgba(82,232,254,1) 100%)",
  ringbackgroundColor: "rgba(255,255,255,1)",
  ringStyle: "roundedcorner",
  innerRadius: 0.72,
  direction: "clockwise",
  fillShape: "normal",
  barWidth: 0.1,
  startAngle: 0,
  endAngle: 360,
  endImageisShow: true,
  endImage: "",
  endImageSize: 0.39,
  endImageOffsetX: 0,
  endImageOffsetY: 0,
  eventConfigures: [],
};
