import type { JsonObject } from "../../types/component.js";

export const infoPannelDefaultProps: JsonObject = {
  componentName: "GaodeMap-InfoPannel",
  name: "信息面板",
  title: "信息面板",
  mapId: "",
  style: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 0,
    height: 0,
    zIndex: 10,
  },
  rotate: 0,
  opacity: 1,
  entryAnimiation: { isShow: false, type: "" },
  eventConfigures: [],
  zooms: {
    min: 2,
    max: 22,
  },
  datasource: {
    autoRefresh: false,
    sourceType: "constant",
    fieldMappings: [
      {
        mapFields: [
          {
            path: "lng",
            deleted: false,
            label: "lng",
          },
        ],
        key: "lng",
      },
      {
        mapFields: [
          {
            path: "lat",
            deleted: false,
            label: "lat",
          },
        ],
        key: "lat",
      },
      {
        mapFields: [
          {
            path: "value1",
            deleted: false,
            label: "value1",
          },
          {
            path: "value2",
            deleted: false,
            label: "value2",
          },
          {
            path: "value3",
            deleted: false,
            label: "value3",
          },
        ],
        key: "value",
      },
      {
        mapFields: [
          {
            path: "state",
            deleted: false,
            label: "state",
          },
        ],
        key: "state",
      },
    ],
    fieldMode: "multiple",
    constantData: [
      {
        value2: 173,
        lng: 118.870825,
        value1: "监测点#02",
        value3: "优",
        state: "优",
        lat: 29.607539,
      },
      {
        value2: 51,
        lng: 120.22345,
        value1: "监测点#03",
        value3: "良",
        state: "良",
        lat: 30.434644,
      },
      {
        value2: 126,
        lng: 119.481674,
        value1: "监测点#01",
        value3: "差",
        state: "差",
        lat: 29.71198,
      },
    ],
  },
  interactionConf: {
    duration: 5,
    camDuration: 2,
    camAnimation: false,
    cancelSelect: true,
    trigger: "hover",
    animation: true,
  },
  markerStyles: [
    {
      bandWidth: 240,
      paddingRight: 0,
      stateValue: "优",
      bandRadius: 0,
      sameRadius: true,
      paddingBottom: 0,
      pointNormalUrl: "group1/M00/05/57/wKgBCWlzpi6EQuL9AAAAADuwBwM125.png",
      bandOffsetY: 0,
      bandOffsetX: 0,
      paddingTop: 0,
      bandBgType: "image",
      bandRadiusRT: 0,
      bandRadiusLT: 0,
      bandUrl: "group1/M00/05/57/wKgBCWlzpb2EdF5ZAAAAADwC0xs200.png",
      pointCurHeight: 45,
      bandHeight: 135,
      bandRadiusRB: 0,
      pointOffsetY: 0,
      bandRadiusLB: 0,
      pointNormalOffsetY: 0,
      pointNormalOffsetX: 0,
      pointNormalHeight: 45,
      pointNormalWidth: 45,
      pointCurWidth: 45,
      pointCurUrl: "group1/M00/05/57/wKgBCWlzpjGEXKw4AAAAAAlds04554.png",
      pointCurOffsetX: 0,
      paddingLeft: 0,
    },
  ],
  textContents: [
    {
      suffixFontFamily: "Microsoft YaHei",
      labelFontFamily: "Microsoft YaHei",
      borderColor: "rgba(30,30,30,1)",
      labelRightMargin: 6,
      contentOffsetX: 34,
      contentOffsetY: 16,
      valueColor: "rgba(255,255,255,1)",
      valueFontWeight: "normal",
      valueRadiusRB: 0,
      valueFontFamily: "Microsoft YaHei",
      valuePaddingRight: 0,
      borderWidth: 1,
      itemRadiusLT: 0,
      valueRadiusLB: 0,
      valuePaddingTop: 0,
      itemRadiusRT: 0,
      valuePaddingLeft: 0,
      labelFontStyle: "normal",
      itemRadiusLB: 0,
      suffixFontSize: 12,
      valueFontStyle: "normal",
      labelFontSize: 18,
      labelFontWeight: "normal",
      valueFontSize: 18,
      suffixFontWeight: "normal",
      valueRadiusRT: 0,
      valueRadiusLT: 0,
      valueRadius: 0,
      valueSameRadius: true,
      labelColor: "rgba(255,255,255,1)",
      itemRadiusRB: 0,
      valuePaddingBottom: 0,
      suffixColor: "rgba(230,247,255,1)",
      suffixFontStyle: "normal",
      labelLeftMargin: 0,
      itemRadius: 0,
      mappingField: "value1",
      itemSameRadius: true,
      suffixLeftMargin: 0,
      mappingDisplayName: "名称",
    },
  ],
  zIndex: 10,
};
