import type { JsonObject } from "../../types/component.js";

export const circularProgressDefaultProps: JsonObject = {
  componentName: "CircularProgress",
  name: "环形进度图",
  rotate: 0,
  opacity: 1,
  style: {
    position: "absolute",
    top: 100,
    left: 100,
    width: 525,
    height: 293,
    backgroundColor: "transparent",
    zIndex: 91,
  },
  entryAnimiation: {
    isShow: false,
    type: "",
  },
  datasource: {
    sourceType: "constant",
    fieldMode: "multiple",
    autoRefresh: false,
    fieldMappings: [
      {
        key: "seriesName",
        mapFields: [{ path: "name", label: "name", deleted: false }],
      },
      {
        key: "value",
        mapFields: [{ path: "value", label: "value", deleted: false }],
      },
    ],
    constantData: [
      { name: "系列1", value: 20 },
      { name: "系列2", value: 50 },
      { name: "系列3", value: 70 },
    ],
  },
  baseSeriesConfig: {
    maxValue: 100,
    minRadius: 0.15,
    gap: 10,
    roundCap: true,
    clockwise: true,
    trackColor: "rgba(255,255,255,0.12)",
    showLabel: true,
    labelColor: "#ffffff",
    labelFontSize: 14,
    labelFontFamily: "Microsoft YaHei",
    labelFontWeight: "normal",
    labelFontStyle: "normal",
    labelShowSeriesName: true,
    precision: 0,
    suffix: "%",
    labelHelpLineColor: "rgba(255,255,255,0.3)",
    labelHelpLineWidth: 1,
    shadowColor: "transparent",
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    shadowBlur: 0,
  },
  customSeriesConfigs: [],
  legendConfig: {
    show: true,
    position: {
      top: "bottom",
      left: "center",
    },
    orient: "horizontal",
    icon: "circle",
    fontFamily: "Microsoft YaHei",
    fontSize: 12,
    color: "#ffffff",
    fontWeight: "normal",
    fontStyle: "normal",
  },
  tooltipConfig: {
    show: true,
    backgroundColor: "rgba(3,16,31,0.92)",
    fontFamily: "Microsoft YaHei",
    fontSize: 14,
    color: "#ffffff",
    fontWeight: "normal",
    fontStyle: "normal",
  },
  animationConfig: {
    show: true,
    duration: 1000,
    closeAnimationOnDesignMode: true,
  },
  eventConfigures: [],
};
