import type { JsonObject } from "../../types/component.js";

export const inputDefaultProps: JsonObject = {
  componentName: "Input",
  name: "输入框",
  title: "输入框",
  inputType: "string",
  defaultValue: "",
  placeholder: "请输入",
  debounceTime: 300,
  min: 0,
  max: 100,
  precision: 0,
  step: 1,
  backgroundType: "color",
  backgroundColor: "rgba(224,242,253,0.09411764705882353)",
  backgroundImage: "",
  border: {
    color: "rgba(230,245,255,1)",
    show: true,
    width: 0.5,
    radius: 8,
  },
  placeholderStyle: {
    color: "rgba(170,175,183,1)",
    textAlign: "left",
    fontSize: 16,
  },
  style: {
    top: 338.2530120481928,
    color: "rgba(255,255,255,1)",
    left: 590.1204819277109,
    textAlign: "left",
    width: 120,
    fontSize: 16,
    position: "absolute",
    height: 48,
    zIndex: 53,
    fontFamily:
      '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
    fontStyle: "normal",
    fontWeight: "normal",
    letterSpacing: 0,
    lineHeight: 1,
    backgroundColor: "transparent",
  },
  rotate: 0,
  opacity: 1,
  eventConfigures: [],
  entryAnimiation: {
    type: "",
    isShow: false,
  },
};
