import type { JsonObject } from "../../types/component.js";

export const navMenuDefaultProps: JsonObject = {
  componentName: "NavMenu",
  name: "导航菜单",
  title: "导航菜单",
  style: {
    position: "absolute",
    left: 400,
    top: 400,
    width: 280,
    height: 420,
    rotate: 0,
    opacity: 1,
    zIndex: 1,
    backgroundColor: "rgba(9,18,32,0.92)",
  },
  rotate: 0,
  opacity: 1,
  menuData: {
    originalData: [
      {
        id: "1",
        name: "菜单1",
        icon: "group1/M00/03/FE/wKgBCWP8EeiAHj9rAAAGMWTcl1g322.svg",
        children: [
          {
            id: "2",
            name: "菜单1-1",
            icon: "group1/M00/03/FE/wKgBCWP8EeiAHj9rAAAGMWTcl1g322.svg",
            children: [
              {
                id: "3",
                name: "菜单1-1-1",
                icon: "group1/M00/03/FE/wKgBCWP8EeiAHj9rAAAGMWTcl1g322.svg",
              },
              {
                id: "4",
                name: "菜单1-1-2",
                icon: "group1/M00/03/FE/wKgBCWP8EeiAHj9rAAAGMWTcl1g322.svg",
              },
              {
                id: "5",
                name: "菜单1-1-3",
                icon: "group1/M00/03/FE/wKgBCWP8EeiAHj9rAAAGMWTcl1g322.svg",
              },
            ],
          },
        ],
      },
      {
        id: "6",
        name: "菜单2",
        icon: "group1/M00/03/FE/wKgBCWP8EeiAHj9rAAAGMWTcl1g322.svg",
      },
      {
        id: "7",
        name: "菜单3",
        icon: "group1/M00/03/FE/wKgBCWP8EeiAHj9rAAAGMWTcl1g322.svg",
      },
      {
        id: "8",
        name: "菜单4",
        icon: "group1/M00/03/FE/wKgBCWP8EeiAHj9rAAAGMWTcl1g322.svg",
      },
      {
        id: "9",
        name: "菜单5",
        icon: "group1/M00/03/FE/wKgBCWP8EeiAHj9rAAAGMWTcl1g322.svg",
      },
    ],
    tableMapData: {
      id: "id",
      name: "name",
      icon: "icon",
      children: "children",
    },
    originType: "static",
  },
  defaultSelectedId: "1",
  isExpand: false,
  indentSize: 20,
  itemHeight: 40,
  itemGap: 4,
  itemBorderRadius: 4,
  expandIconColor: "#94A3B8",
  showIcon: true,
  iconSize: 16,
  expandIconSize: 12,
  iconSpace: 10,
  textOverflow: "ellipsis",
  showTooltip: true,
  menuDefaultStyle: {
    iconColor: "#94A3B8",
    fontFamily:
      '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
    fontSize: 14,
    color: "#CBD5E1",
    textAlign: "flex-start",
    backgroundColor: "transparent",
    fontStyle: "normal",
    fontWeight: "normal",
    letterSpacing: 0,
    lineHeight: 1.5,
  },
  menuHoverStyle: {
    iconColor: "#E2E8F0",
    fontFamily:
      '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
    fontSize: 14,
    color: "#F8FAFC",
    textAlign: "flex-start",
    backgroundColor: "rgba(148,163,184,0.12)",
    fontStyle: "normal",
    fontWeight: "normal",
    letterSpacing: 0,
    lineHeight: 1.5,
  },
  menuSelectStyle: {
    iconColor: "#FFFFFF",
    fontFamily:
      '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
    fontSize: 14,
    color: "#FFFFFF",
    textAlign: "flex-start",
    backgroundColor: "rgba(37,99,235,0.32)",
    fontStyle: "normal",
    fontWeight: "bold",
    letterSpacing: 0,
    lineHeight: 1.5,
  },
  eventConfigures: [],
  entryAnimiation: {
    isShow: false,
    type: "",
  },
};
