export const pieChartDefaultProps = {
    componentName: "PieChart",
    rotate: 0,
    chartData: {
        isPolling: false,
        indicator: [
            {
                fieldDataConfig: {
                    calculateType: "SUM",
                    format: {
                        numberFormat: "numerical",
                        Millimeter: false,
                        accuracy: 2,
                        dataFix: {
                            preFix: "",
                            auFix: "",
                        },
                    },
                    chartDisplayName: "value",
                },
                fieldName: "value",
                fieldDisplayName: "value",
                fieldType: "DECIMAL",
            },
        ],
        constant: {
            data: [
                { name: "类目1", type: "系列", value: 101 },
                { name: "类目2", type: "系列", value: 71 },
                { name: "类目3", type: "系列", value: 121 },
                { name: "类目4", type: "系列", value: 95 },
                { name: "类目5", type: "系列", value: 141 },
                { name: "类目6", type: "系列", value: 96 },
            ],
            originalData: [
                { name: "类目1", type: "系列", value: 101 },
                { name: "类目2", type: "系列", value: 71 },
                { name: "类目3", type: "系列", value: 121 },
                { name: "类目4", type: "系列", value: 95 },
                { name: "类目5", type: "系列", value: 141 },
                { name: "类目6", type: "系列", value: 96 },
            ],
            fieldList: [
                {
                    fieldName: "name",
                    fieldDisplayName: "name",
                    fieldType: "LONGTEXT",
                },
                {
                    fieldName: "type",
                    fieldDisplayName: "type",
                    fieldType: "LONGTEXT",
                },
                {
                    fieldName: "value",
                    fieldDisplayName: "value",
                    fieldType: "DECIMAL",
                },
            ],
        },
        form: {
            formPermType: "All",
            formUuid: "",
            formName: "",
        },
        sourceType: "constant",
        api: {
            headers: [],
            processFunction: "function handleResponse (response) { return response }",
            requestBody: "",
            requestParam: [],
            fieldList: [],
            apiUuid: "",
        },
        polling: 3,
        dimension: [
            {
                fieldDataConfig: {
                    calculateType: "COUNT",
                    chartDisplayName: "name",
                },
                fieldName: "name",
                fieldDisplayName: "name",
                fieldType: "LONGTEXT",
            },
        ],
    },
    eventConfigures: [],
    advanced: true,
    entryAnimiation: {
        type: "",
        isShow: false,
    },
    name: "Pie Chart",
    style: {
        top: 72,
        left: 669,
        width: 400,
        position: "absolute",
        height: 226,
        zIndex: 500,
    },
    opacity: 1,
    option: {
        backgroundColor: "#003552cf",
        color: [
            "#5470c6",
            "#fac858",
            "#ee6666",
            "#73c0de",
            "#3ba272",
            "#fc8452",
            "#9a60b4",
            "#ea7ccc",
        ],
        animiation: {
            show: false,
            type: "",
        },
        legend: {
            top: "top",
            orient: "horizontal",
            left: "center",
            offsetX: 0,
            offsetY: 0,
            itemHeight: 12,
            show: true,
            icon: "circle",
            itemWidth: 18,
            textStyle: {
                fontFamily: "serif",
                color: "#ffffff",
                fontSize: 11,
                fontStyle: "italic",
                fontWeight: "bold",
            },
        },
        series: [
            {
                hoverAnimation: false,
                left: 10,
                center: ["50%", "50%"],
                name: "",
                itemStyle: {
                    borderType: "solid",
                    borderColor: "#666666",
                    shadowBlur: 0,
                    borderWidth: 2,
                    shadowColor: "#fff",
                },
                mapName: "",
                label: {
                    formatter: "{b}:{c}",
                    fontFamily: "serif",
                    color: "#ffffff",
                    show: true,
                    fontSize: 14,
                    position: "outside",
                    fontStyle: "normal",
                    fontWeight: "bold",
                },
                labelLine: {
                    length2: 40,
                    show: true,
                    length: 22,
                },
                type: "pie",
                radius: ["0%", "60%"],
            },
        ],
        tooltip: {
            backgroundColor: "#333",
            show: true,
            axisPointer: {
                label: {
                    show: false,
                },
                type: "shadow",
            },
            textStyle: {
                fontFamily: "serif",
                color: "#fff",
                fontSize: 14,
                fontStyle: "normal",
                fontWeight: "normal",
            },
        },
    },
};
