import type { JsonObject } from "../../types/component.js";

export const threeDPieChartDefaultProps: JsonObject = {
  componentName: "ThreeDPieChart",
  rotate: 0,
  chartData: {
    isPolling: false,
    indicator: [
      {
        fieldDataConfig: {
          calculateType: "SUM",
          format: {
            numberFormat: "numerical",
            Millimeter: false,
            accuracy: 2,
            dataFix: {
              preFix: "",
              auFix: "",
            },
          },
          chartDisplayName: "value",
        },
        fieldName: "value",
        fieldDisplayName: "value",
        fieldType: "DECIMAL",
      },
    ],
    constant: {
      data: [
        { name: "系列一", type: "系列", value: 51.6 },
        { name: "系列二", type: "系列", value: 18.4 },
        { name: "系列三", type: "系列", value: 11.8 },
        { name: "系列四", type: "系列", value: 9.6 },
        { name: "系列五", type: "系列", value: 8.6 },
      ],
      originalData: [
        { name: "系列一", type: "系列", value: 51.6 },
        { name: "系列二", type: "系列", value: 18.4 },
        { name: "系列三", type: "系列", value: 11.8 },
        { name: "系列四", type: "系列", value: 9.6 },
        { name: "系列五", type: "系列", value: 8.6 },
      ],
      fieldList: [
        {
          fieldName: "name",
          fieldDisplayName: "name",
          fieldType: "LONGTEXT",
        },
        {
          fieldName: "type",
          fieldDisplayName: "type",
          fieldType: "LONGTEXT",
        },
        {
          fieldName: "value",
          fieldDisplayName: "value",
          fieldType: "DECIMAL",
        },
      ],
    },
    form: {
      formPermType: "All",
      formUuid: "",
      formName: "",
    },
    sourceType: "constant",
    api: {
      headers: [],
      processFunction: "function handleResponse (response) { return response }",
      requestBody: "",
      requestParam: [],
      fieldList: [],
      apiUuid: "",
    },
    polling: 3,
    dimension: [
      {
        fieldDataConfig: {
          calculateType: "COUNT",
          chartDisplayName: "name",
        },
        fieldName: "name",
        fieldDisplayName: "name",
        fieldType: "LONGTEXT",
      },
    ],
  },
  eventConfigures: [],
  advanced: true,
  entryAnimiation: {
    type: "",
    isShow: false,
  },
  name: "3D Pie Chart",
  style: {
    top: 72,
    left: 669,
    width: 400,
    position: "absolute",
    height: 280,
    zIndex: 500,
  },
  opacity: 1,
  option: {
    backgroundColor: "transparent",
    color: ["#22D8F2", "#28B8FF", "#6A8EFF", "#C7F5E5", "#91F3C7"],
    animiation: {
      show: false,
      type: "",
    },
    animation: {
      show: false,
      type: "",
    },
    legend: {
      show: true,
      icon: "rect",
      left: "center",
      top: "bottom",
      orient: "horizontal",
      itemWidth: 14,
      itemHeight: 14,
      textStyle: {
        color: "#111111",
        fontSize: 14,
        fontWeight: "normal",
        fontStyle: "normal",
        fontFamily: "Microsoft YaHei",
      },
    },
    threeDSettings: {
      activeIndex: 0,
      animationEnabled: true,
      centerLabelVisible: true,
      rotation: 14,
      animationDuration: 2200,
      liftDistance: 14,
      depth: 18,
      tilt: 63,
      topViewAngle: 63,
      interactionTrigger: "hover",
      projectionType: "perspective",
      pixelRatio: 1.5,
      cameraPosition: {
        x: 0,
        y: -2,
        z: 220,
      },
      cameraRotation: {
        x: -4,
        y: 0,
        z: 0,
      },
      outerRadiusScale: 0.82,
      innerRadiusScale: 0.74,
      centerYRatio: 0.48,
      centerYOffset: 4,
    },
    tooltip: {
      show: true,
      backgroundColor: "#121821",
      textStyle: {
        color: "#fff",
        fontWeight: "normal",
        fontSize: 12,
        fontStyle: "normal",
        fontFamily: "Microsoft YaHei",
      },
    },
    series: [
      {
        name: "",
        mapName: "",
        type: "pie",
        left: 0,
        radius: ["72%", "96%"],
        center: ["50%", "48%"],
        hoverAnimation: false,
        itemStyle: {
          borderWidth: 0.8,
          borderColor: "#D7F7FF",
          borderType: "solid",
          shadowBlur: 0,
          shadowColor: "#ffffff",
        },
        label: {
          show: false,
          formatter: "{d}%",
          position: "outside",
          fontWeight: "bold",
          color: "#ffffff",
          fontSize: 14,
          fontStyle: "normal",
          fontFamily: "Microsoft YaHei",
        },
        labelLine: {
          show: false,
          length: 24,
          length2: 36,
          color: "#ffffff",
          width: 1.8,
        },
      },
    ],
  },
};
