import type { JsonObject } from "../../types/component.js";

export const optionButtonDefaultProps: JsonObject = {
  componentName: "optionButton",
  name: "操作按钮",
  title: "操作按钮",
  btnText: "操作按钮",
  btnTextAlign: "flex-start",
  defaultSelect: false,
  showIcon: true,
  iconSize: 36,
  iconSpace: 20,
  arrange: "row",
  btnIcon: {
    iconSrc: "group1/M00/03/FE/wKgBCWP8EzGALm14AAAE_uQ--qo915.svg",
    iconType: "systemIcon",
  },
  btnDefaultStyle: {
    iconColor: "rgba(198,228,255,1)",
    fontFamily:
      '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
    fontSize: 22,
    color: "rgba(198,228,255,1)",
    textAlign: "flex-start",
    backgroundColor: "rgba(47,125,220,0.6899)",
    fontStyle: "normal",
    fontWeight: "bold",
    letterSpacing: 2,
    lineHeight: 2,
    borderWidth: 2,
    borderColor: "rgba(109,174,255,0.77)",
    borderRadius: 10,
    borderStyle: "solid",
  },
  btnHoverStyle: {
    iconColor: "rgba(212,233,252,1)",
    fontFamily:
      '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
    fontSize: 22,
    color: "rgba(212,233,252,1)",
    textAlign: "flex-start",
    backgroundColor: "rgba(47,125,220,0.85)",
    fontStyle: "normal",
    fontWeight: "bold",
    letterSpacing: 2,
    lineHeight: 2,
    borderWidth: 2,
    borderColor: "rgba(97,163,245,0.77)",
    borderRadius: 10,
    borderStyle: "solid",
  },
  btnSelectStyle: {
    iconColor: "rgba(254,254,254,1)",
    fontFamily:
      '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
    fontSize: 22,
    color: "rgba(255,255,255,1)",
    textAlign: "flex-start",
    backgroundColor: "rgba(32,111,211,0.88)",
    fontStyle: "normal",
    fontWeight: "bold",
    letterSpacing: 2,
    lineHeight: 2,
    borderWidth: 2,
    borderColor: "rgba(111,175,254,1)",
    borderRadius: 10,
    borderStyle: "solid",
  },
  style: {
    position: "absolute",
    left: 400,
    top: 400,
    width: 185,
    height: 60,
    zIndex: 1,
  },
  rotate: 0,
  opacity: 1,
  eventConfigures: [],
  entryAnimiation: {
    isShow: false,
    type: "",
  },
};
