import type { JsonObject } from "../../types/component.js";

export const swiperDefaultProps: JsonObject = {
  componentName: "Swiper",
  name: "轮播图",
  title: "轮播图",
  imageSrcList: [],
  imageShowType: "noRepeat",
  direction: "horizontal",
  navigation: {
    isActive: false,
    position: "inner",
    size: {
      width: 30,
      height: 16,
      borderRadius: 0,
    },
    backgroundColor: "#ffffff00",
    color: "#ffffff",
    arrow: "none",
    navigation: false,
  },
  swiperAnimation: {
    isActive: true,
    animationType: "slide",
    loop: true,
    delayTime: 3,
  },
  animation: {
    isActive: false,
    isLoop: false,
    speed: "linear",
    duration: 2,
    delay: 0,
    type: "opacity",
  },
  transform3D: {
    isActive: false,
    rotateX: 0,
    rotateY: 0,
    rotateZ: 0,
  },
  targetUrl: "",
  openBrowser: false,
  style: {
    position: "absolute",
    left: 400,
    top: 400,
    width: 1000,
    height: 300,
    zIndex: 1,
    fontFamily:
      '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
    fontSize: 18,
    color: "#fff",
    textAlign: "center",
    fontStyle: "normal",
    fontWeight: "normal",
    letterSpacing: 1,
    lineHeight: 2,
  },
  rotate: 0,
  opacity: 1,
  eventConfigures: [],
  entryAnimiation: {
    isShow: false,
    type: "",
  },
};
