import type { JsonObject } from "../../types/component.js";

export const scatterChartDefaultProps: JsonObject = {
  componentName: "ScatterChart",
  rotate: 0,
  chartData: {
    isPolling: false,
    indicator: [
      {
        fieldDataConfig: {
          calculateType: "SUM",
          format: {
            numberFormat: "numerical",
            Millimeter: false,
            accuracy: 2,
            dataFix: {
              preFix: "",
              auFix: "",
            },
          },
          chartDisplayName: "x",
        },
        fieldName: "x",
        fieldDisplayName: "x",
        fieldType: "DECIMAL",
      },
      {
        fieldDataConfig: {
          calculateType: "SUM",
          format: {
            numberFormat: "numerical",
            Millimeter: false,
            accuracy: 2,
            dataFix: {
              preFix: "",
              auFix: "",
            },
          },
          chartDisplayName: "y",
        },
        fieldName: "y",
        fieldDisplayName: "y",
        fieldType: "DECIMAL",
      },
      {
        fieldDataConfig: {
          calculateType: "SUM",
          format: {
            numberFormat: "numerical",
            Millimeter: false,
            accuracy: 2,
            dataFix: {
              preFix: "",
              auFix: "",
            },
          },
          chartDisplayName: "size",
        },
        fieldName: "size",
        fieldDisplayName: "size",
        fieldType: "DECIMAL",
      },
    ],
    constant: {
      data: [
        { x: 12, y: 34, size: 18, series: "系列1" },
        { x: 28, y: 56, size: 24, series: "系列1" },
        { x: 45, y: 21, size: 14, series: "系列1" },
        { x: 63, y: 78, size: 32, series: "系列2" },
        { x: 80, y: 45, size: 20, series: "系列2" },
        { x: 55, y: 67, size: 28, series: "系列2" },
      ],
      originalData: [
        { x: 12, y: 34, size: 18, series: "系列1" },
        { x: 28, y: 56, size: 24, series: "系列1" },
        { x: 45, y: 21, size: 14, series: "系列1" },
        { x: 63, y: 78, size: 32, series: "系列2" },
        { x: 80, y: 45, size: 20, series: "系列2" },
        { x: 55, y: 67, size: 28, series: "系列2" },
      ],
      fieldList: [
        { fieldName: "x", fieldDisplayName: "x", fieldType: "DECIMAL" },
        { fieldName: "y", fieldDisplayName: "y", fieldType: "DECIMAL" },
        { fieldName: "size", fieldDisplayName: "size", fieldType: "DECIMAL" },
        { fieldName: "series", fieldDisplayName: "series", fieldType: "LONGTEXT" },
      ],
    },
    form: {
      formPermType: "All",
      formUuid: "",
      formName: "",
    },
    sourceType: "constant",
    api: {
      headers: [],
      processFunction: "function handleResponse (response) { return response }",
      requestBody: "",
      requestParam: [],
      fieldList: [],
      apiUuid: "",
    },
    polling: 3,
    dimension: [
      {
        fieldDataConfig: {
          calculateType: "COUNT",
          chartDisplayName: "series",
        },
        fieldName: "series",
        fieldDisplayName: "series",
        fieldType: "LONGTEXT",
      },
    ],
  },
  eventConfigures: [],
  advanced: true,
  entryAnimiation: {
    type: "",
    isShow: false,
  },
  name: "Scatter Chart",
  style: {
    top: 72,
    left: 669,
    width: 400,
    position: "absolute",
    height: 226,
    zIndex: 500,
  },
  opacity: 1,
  option: {
    backgroundColor: "transparent",
    color: [
      "#5470c6",
      "#fac858",
      "#ee6666",
      "#73c0de",
      "#3ba272",
      "#fc8452",
      "#9a60b4",
      "#ea7ccc",
    ],
    animiation: {
      show: false,
      type: "",
    },
    tooltip: {
      trigger: "item",
      show: true,
      backgroundColor: "rgba(3,16,31,0.92)",
      borderColor: "rgba(0,229,255,0.35)",
      borderWidth: 1,
      textStyle: {
        color: "#fff",
        fontWeight: "normal",
        fontSize: 14,
        fontStyle: "normal",
        fontFamily: "serif",
      },
      axisPointer: {
        type: "none",
      },
    },
    grid: {
      left: 30,
      top: 50,
      bottom: 38,
      right: 22,
    },
    legend: {
      show: true,
      left: "center",
      top: "top",
      orient: "horizontal",
      itemWidth: 18,
      itemHeight: 12,
      textStyle: {
        color: "#ffffff",
        fontSize: 14,
        fontWeight: "normal",
        fontFamily: "serif",
        fontStyle: "normal",
      },
      icon: "",
    },
    xAxis: {
      type: "value",
      show: true,
      name: "",
      axisTick: {
        show: false,
        inside: true,
        length: 10,
        lineStyle: {
          width: 3,
          type: "solid",
          color: "#fff",
        },
      },
      axisLine: {
        show: true,
        inside: false,
        lineStyle: {
          color: "#ffffff",
          width: 1,
          type: "solid",
        },
      },
      splitLine: {
        show: true,
        lineStyle: {
          color: "#e6f7ff",
          width: 1,
          type: "dashed",
        },
      },
      axisLabel: {
        show: true,
        inside: false,
        rotate: 0,
        color: "#e6f7ff",
        fontWeight: "normal",
        fontFamily: "serif",
        fontSize: 12,
        fontStyle: "normal",
        align: "center",
        margin: 8,
      },
    },
    yAxis: {
      type: "value",
      show: true,
      name: "",
      axisTick: {
        show: false,
        inside: true,
        length: 10,
        lineStyle: {
          width: 3,
          type: "solid",
          color: "#fff",
        },
      },
      axisLine: {
        show: true,
        inside: false,
        lineStyle: {
          color: "#ffffff",
          width: 1,
          type: "solid",
        },
      },
      splitLine: {
        show: true,
        lineStyle: {
          color: "#e6f7ff",
          width: 1,
          type: "dashed",
        },
      },
      axisLabel: {
        show: true,
        inside: false,
        rotate: 0,
        color: "#e6f7ff",
        fontWeight: "normal",
        fontFamily: "serif",
        fontStyle: "normal",
        align: "center",
        formatter: "{value}",
        fontSize: 12,
        margin: 8,
      },
    },
    series: [
      {
        __seriesType: "__default",
        name: "",
        mapName: "",
        type: "scatter",
        symbol: "circle",
        itemStyle: {
          opacity: 0.8,
          borderWidth: 0,
          borderColor: "#666666",
          borderType: "solid",
          shadowBlur: 0,
          shadowColor: "#fff",
          color: "",
        },
        label: {
          show: false,
          position: "top",
          fontWeight: "bold",
          color: "#ffffff",
          fontSize: 12,
          fontStyle: "normal",
          fontFamily: "serif",
          rotate: 0,
          formatter: "{c}",
        },
        __fixedSize: 30,
        __bubbleSize: {
          enable: true,
          minSize: 10,
          maxSize: 30,
        },
      },
    ],
  },
};
