import type { JsonObject } from "../../types/component.js";
import { buildSelectDataConfig } from "../form-utils.js";

export const selectDefaultProps: JsonObject = {
  componentName: "Select",
  name: "下拉选择",
  title: "下拉选择",
  defaultSelectedType: "index",
  defaultSelectedIndex: 1,
  allowClear: true,
  dropdownDebugFlag: false,
  dataConfig: buildSelectDataConfig(undefined),
  selector: {
    paddingLeft: 12,
    selected: {
      style: {
        color: "rgba(255,255,255,1)",
        textAlign: "left",
        fontSize: 16,
        fontWeight: "normal",
      },
    },
    placeholder: {
      style: {
        color: "rgba(170,175,183,1)",
        textAlign: "left",
        fontSize: 16,
      },
      content: "请选择",
    },
    backgroundType: "color",
    backgroundColor: "rgba(224,242,253,0.09411764705882353)",
    backgroundImage: "",
    border: {
      color: "rgba(230,245,255,1)",
      show: true,
      width: 0.5,
      radius: 8,
    },
    dropdownIcon: {
      imageUrl: "group1/M00/04/CD/wKgBCWgRsTSEN2hMAAAAAKgk5vQ327.svg",
      width: 16,
      height: 16,
      rightPadding: 8,
    },
    selectedIcon: {
      imageUrl: "",
      width: 16,
      height: 16,
      leftPadding: 8,
    },
  },
  dropdown: {
    direction: "bottom",
    animationDuration: 200,
    height: 200,
    offsetTop: 4,
    scrollbarWidth: "thin",
    scrollbarTrackColor: "rgba(255,255,255,0)",
    scrollbarThumbColor: "rgba(255,255,255,0.3)",
    optionHeight: 28,
    optionPadding: 8,
    optionSpacing: 4,
    defaultOption: {
      style: {
        color: "rgba(255,255,255,0.8)",
        textAlign: "left",
        fontFamily:
          '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
        fontSize: 14,
        fontWeight: "normal",
        fontStyle: "normal",
        letterSpacing: 0,
        lineHeight: 1.5,
      },
      backgroundFillType: "color",
      backgroundFillColor: "rgba(224,242,253,0)",
      backgroundFillImage: "",
    },
    selectedOption: {
      style: {
        color: "rgba(255,255,255,1)",
        textAlign: "left",
        fontFamily:
          '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
        fontSize: 14,
        fontWeight: "normal",
        fontStyle: "normal",
        letterSpacing: 0,
        lineHeight: 1.5,
      },
      backgroundFillType: "color",
      backgroundFillColor: "rgba(133,167,191,0.24)",
      backgroundFillImage: "",
    },
    hoverOption: {
      style: {
        color: "rgba(255,255,255,0.8)",
        textAlign: "left",
        fontFamily:
          '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
        fontSize: 14,
        fontWeight: "normal",
        fontStyle: "normal",
        letterSpacing: 0,
        lineHeight: 1.5,
      },
      backgroundFillType: "color",
      backgroundFillColor: "rgba(133,167,191,0.13333333333333333)",
      backgroundFillImage: "",
    },
    placement: "bottomLeft",
    backgroundColor: "rgba(24,39,55,0.8)",
  },
  style: {
    position: "absolute",
    left: 100,
    top: 100,
    width: 200,
    height: 48,
    zIndex: 10,
    fontFamily:
      '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
    fontSize: 16,
    color: "rgba(255,255,255,1)",
    textAlign: "left",
    backgroundColor: "transparent",
    fontStyle: "normal",
    fontWeight: "normal",
    letterSpacing: 0,
    lineHeight: 1,
  },
  rotate: 0,
  opacity: 1,
  eventConfigures: [],
  entryAnimiation: {
    isShow: false,
    type: "",
  },
};
