import type { JsonObject } from "../../types/component.js";

export const indicatorCapability: JsonObject = {
  componentName: "Indicator",
  displayName: "翻牌器",
  description: "用于大屏关键指标翻牌动画展示，支持标题、前后缀、千分位、小数位数与数字背景配置。",
  aiRole:
    "AI 负责数值、标题、前后缀、位置、尺寸、字体样式与动画开关；MCP 负责把 textValue 同步到 chartData 并补齐其余 props。",
  requiredProps: [
    {
      path: "componentName",
      type: "string",
      value: "Indicator",
      description: "组件类型，必须固定为 Indicator。",
    },
    {
      path: "logicalId",
      type: "string",
      description: "组件唯一 ID，由 AI 生成；后端限制最长 50 个字符，必须包含短随机段以保证大屏内全局唯一。",
    },
    {
      path: "parentLogicalId",
      type: "string",
      description: "父级组件或分组 ID，由 AI 生成。",
    },
    {
      path: "style",
      type: "object",
      description: "组件在大屏画布上的位置、尺寸和背景。",
      children: [
        { path: "style.left", type: "number", description: "画布左侧距离。" },
        { path: "style.top", type: "number", description: "画布顶部距离。" },
        { path: "style.width", type: "number", description: "组件宽度。" },
        { path: "style.height", type: "number", description: "组件高度。" },
        {
          path: "style.position",
          type: "string",
          value: "absolute",
          description: "固定使用 absolute。",
        },
      ],
    },
  ],
  aiWritableProps: [
    { path: "name", type: "string", description: "图层名称。" },
    {
      path: "textValue",
      type: "number",
      description: "要展示的翻牌数值。MCP 会同步写入 chartData.constant.data[0].value。",
    },
    {
      path: "titleName",
      type: "string",
      description: "标题文案，为空时默认显示指标字段名。",
    },
    {
      path: "titleVisible",
      type: "boolean",
      description: "是否显示标题。",
    },
    {
      path: "globalConfig",
      type: "object",
      description: "标题与数字的整体布局配置。",
    },
    {
      path: "globalConfig.flexDirection",
      type: "enum",
      values: ["column", "column-reverse", "inherit", "row-reverse"],
      description:
        "标题与数字的排列方向。column=标题在上、数字在下；column-reverse=标题在下、数字在上；inherit=标题在左、数字在右；row-reverse=标题在右、数字在左。",
    },
    {
      path: "globalConfig.alignItems",
      type: "enum",
      values: ["flex-start", "center", "flex-end", "baseline", "stretch"],
      description:
        "交叉轴对齐方式。垂直排列时对应 align-items（标题/数字在组件内的水平对齐）；水平排列时对应 justify-content（标题/数字在组件内的垂直对齐）。",
    },
    {
      path: "globalConfig.space",
      type: "number",
      description:
        "标题与数字之间的间距（px）。注意：该值会同时作为标题和数字的外边距，因此视觉上两者的真实间距约为 2*space。建议 space 取 2~8。",
    },
    {
      path: "titleStyle",
      type: "object",
      description: "标题字体样式。",
      children: [
        { path: "titleStyle.fontFamily", type: "string", description: "字体族。" },
        { path: "titleStyle.fontSize", type: "number", description: "字号（px），建议 14~24。" },
        { path: "titleStyle.color", type: "string", description: "字体颜色，支持 hex / rgba。" },
        { path: "titleStyle.fontWeight", type: "enum", values: ["normal", "bold", "bolder"], description: "粗细。" },
        { path: "titleStyle.fontStyle", type: "enum", values: ["normal", "italic", "oblique"], description: "斜体。" },
        { path: "titleStyle.letterSpacing", type: "number", description: "字距（px）。" },
        { path: "titleStyle.lineHeight", type: "number", description: "行高。" },
      ],
    },
    {
      path: "numberStyle",
      type: "object",
      description:
        "数字字体样式。注意：numberStyle.letterSpacing 会被用作相邻数字/小数点之间的水平间隙（margin），因此不建议设置过大，推荐 0~4。",
      children: [
        { path: "numberStyle.fontFamily", type: "string", description: "字体族。" },
        { path: "numberStyle.fontSize", type: "number", description: "字号（px），建议 32~72，需保证组件高度足够。" },
        { path: "numberStyle.color", type: "string", description: "字体颜色，建议科技风高亮色如 #00E5FF。" },
        { path: "numberStyle.fontWeight", type: "enum", values: ["normal", "bold", "bolder"], description: "粗细。" },
        { path: "numberStyle.fontStyle", type: "enum", values: ["normal", "italic", "oblique"], description: "斜体。" },
        { path: "numberStyle.letterSpacing", type: "number", description: "数字间隙（px），推荐 0~4。" },
        { path: "numberStyle.lineHeight", type: "number", description: "行高，无数字背景时生效。" },
      ],
    },
    {
      path: "prefix",
      type: "boolean",
      description: "是否显示前缀。",
    },
    {
      path: "prefixTitle",
      type: "string",
      description: "前缀文案，例如“¥”。",
    },
    {
      path: "prefixStyle",
      type: "object",
      description: "前缀样式。isFollowPrefix=true 时，prefixStyle 会被 numberStyle 覆盖。",
      children: [
        { path: "prefixStyle.fontSize", type: "number", description: "字号（px）。" },
        { path: "prefixStyle.color", type: "string", description: "字体颜色。" },
        { path: "prefixStyle.fontWeight", type: "enum", values: ["normal", "bold", "bolder"], description: "粗细。" },
        { path: "prefixStyle.alignSelf", type: "enum", values: ["start", "center", "end"], description: "垂直对齐。" },
      ],
    },
    {
      path: "isFollowPrefix",
      type: "boolean",
      description: "前缀是否跟随数字样式。",
    },
    {
      path: "suffix",
      type: "boolean",
      description: "是否显示后缀。",
    },
    {
      path: "suffixTitle",
      type: "string",
      description: "后缀文案，例如“%”。",
    },
    {
      path: "suffixStyle",
      type: "object",
      description: "后缀样式。isFollowSuffix=true 时，suffixStyle 会被 numberStyle 覆盖。",
      children: [
        { path: "suffixStyle.fontSize", type: "number", description: "字号（px）。" },
        { path: "suffixStyle.color", type: "string", description: "字体颜色。" },
        { path: "suffixStyle.fontWeight", type: "enum", values: ["normal", "bold", "bolder"], description: "粗细。" },
        { path: "suffixStyle.alignSelf", type: "enum", values: ["start", "center", "end"], description: "垂直对齐。" },
      ],
    },
    {
      path: "isFollowSuffix",
      type: "boolean",
      description: "后缀是否跟随数字样式。",
    },
    {
      path: "decimal",
      type: "number",
      range: [0, 4],
      description: "小数位数，取值 0 到 4。",
    },
    {
      path: "separation",
      type: "boolean",
      description: "是否开启千分位分隔。",
    },
    {
      path: "animation",
      type: "boolean",
      description: "是否开启动画。",
    },
    {
      path: "animateType",
      type: "enum",
      values: [0, 1],
      description: "动画类型：0 为 CountUp，1 为逐位翻牌。",
    },
    {
      path: "duration",
      type: "number",
      description: "动画持续时间（秒）。",
    },
    {
      path: "hasBackground",
      type: "boolean",
      description: "是否为每位数字添加背景。",
    },
    {
      path: "numBackground",
      type: "object",
      description: "数字背景配置：width、height、isBgColor、bgColor、bgImg。开启 hasBackground 后才会生效。",
      children: [
        { path: "numBackground.width", type: "number", description: "单个数字背景宽度（px）。" },
        { path: "numBackground.height", type: "number", description: "单个数字背景高度（px）。" },
        { path: "numBackground.isBgColor", type: "boolean", description: "true=使用背景色，false=使用背景图片。" },
        { path: "numBackground.bgColor", type: "string", description: "背景色（isBgColor=true 时生效）。" },
        { path: "numBackground.bgImg", type: "string", description: "背景图片地址（isBgColor=false 时生效）。" },
      ],
    },
    {
      path: "entryAnimiation",
      type: "object",
      description: "入场动画配置。",
      children: [
        { path: "entryAnimiation.isShow", type: "boolean", description: "是否开启动场动画。" },
        {
          path: "entryAnimiation.type",
          type: "enum",
          values: [
            "animate__fadeInLeft",
            "animate__fadeInRight",
            "animate__fadeInTopLeft",
            "animate__fadeInTopRight",
            "animate__fadeInBottomLeft",
            "animate__fadeInBottomRight",
            "animate__zoomIn",
          ],
          description: "入场动画类型。",
        },
      ],
    },
    { path: "style", type: "object", description: "位置、尺寸、层级与背景色。" },
    { path: "rotate", type: "number", range: [-360, 360], description: "旋转角度。" },
    { path: "opacity", type: "number", range: [0, 1], description: "不透明度。" },
  ],
  aiForbiddenProps: [
    {
      path: "chartData",
      reason: "翻牌器数据源结构由 MCP 根据 textValue 同步维护，AI 不应直接生成。",
    },
    {
      path: "eventConfigures",
      reason: "交互事件暂不由 AI 生成。",
    },
  ],
  mergeRules: [
    "对象按 key 深合并。",
    "chartData 永远使用默认结构，MCP 会把 textValue 同步到 chartData.constant.data[0].value。",
    "decimal 会同步到 chartData.indicator[0].fieldDataConfig.format.accuracy。",
  ],
  visualRules: [
    "Indicator 组件必须保证足够宽度，避免标题、数值、前缀或后缀被挤换行。建议最小宽度 280px；同时显示标题 + 6 位以上数字 + 后缀时，建议使用 360px 及以上。",
    "开启数字背景 hasBackground 时，宽度预算 ≈ (数字位数 + 千分位逗号数 + 小数点) × (numBackground.width + numberStyle.letterSpacing × 2) + 前缀宽度 + 后缀宽度 + 20px 余量。例如 9,876,543.21 共 12 个字符、背景宽 40、字间距 1 时，内容宽度约 504px，加上前缀后缀后组件宽度建议不小于 600px。",
    "未开启数字背景时，宽度预算 ≈ 字体平均字宽 × 字符数 + 前缀宽度 + 后缀宽度 + 20px 余量；字号 40 时单字宽约 24px，应据此估算。",
    "避免 numBackground.width 小于字号实际宽度，否则数字会溢出背景块；一般 numBackground.width 应 ≥ fontSize × 0.75。",
    "当空间不足时，优先缩小 numBackground.width / fontSize、减少 decimal 位数或关闭 separation，而不是让组件换行。",
    "多个 Indicator 横向排列时，应统一尺寸和间距，保持对齐；不要让每个 KPI 卡片大小或背景风格差异过大。",
    "标题、数值、后缀应保持同一行或清晰的两行布局；禁止出现数值被截断、suffix 被挤到第三行的情况。",
    "Indicator 背景应使用与所属面板/大屏主题协调的弱透明色或 Tech 边框，不要默认使用高饱和纯色背景。",
    "numberStyle.fontSize 与组件高度需匹配：单列布局时建议 height ≥ fontSize * 1.6；数字带背景时建议 height ≥ numBackground.height + 20。",
    "numberStyle.letterSpacing 实际表现为数字间距，推荐 0~4；设置过大将导致数字被撑开并可能溢出。",
    "globalConfig.space 会同时作用于标题和数字，视觉上真实间距约为 2*space；如需 8px 间距可设置 space=4。",
    "前缀/后缀开启时，应预留额外宽度，避免 prefix/suffix 与数字重叠或换行。",
  ],
  examples: [
    {
      title: "关键指标翻牌器",
      props: {
        componentName: "Indicator",
        logicalId: "indicator_sales",
        parentLogicalId: "kpi_group",
        name: "销售额",
        textValue: 1234567.89,
        decimal: 2,
        separation: true,
        titleName: "销售额",
        titleVisible: true,
        prefix: true,
        prefixTitle: "¥",
        animation: true,
        animateType: 1,
        duration: 2,
        hasBackground: false,
        entryAnimiation: {
          isShow: true,
          type: "animate__zoomIn",
        },
        globalConfig: {
          flexDirection: "column",
          alignItems: "center",
          space: 4,
        },
        titleStyle: {
          fontSize: 18,
          color: "rgba(255,255,255,0.85)",
          fontWeight: "normal",
        },
        numberStyle: {
          fontSize: 48,
          color: "#00E5FF",
          fontWeight: "bold",
          letterSpacing: 1,
        },
        style: {
          position: "absolute",
          left: 400,
          top: 400,
          width: 460,
          height: 100,
          zIndex: 1,
          backgroundColor: "rgba(0,229,255,0.06)",
          borderWidth: 1,
          borderStyle: "solid",
          borderColor: "rgba(0,229,255,0.22)",
        },
      },
    },
  ],
};
