import type { JsonObject } from "../../types/component.js";

const STANDARD_FONT_FAMILY =
  '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif';

export const indicatorDefaultProps: JsonObject = {
  componentName: "Indicator",
  name: "翻牌器",
  textValue: 12480,
  chartData: {
    isPolling: false,
    indicator: [
      {
        fieldDataConfig: {
          calculateType: "SUM",
          format: {
            numberFormat: "numerical",
            Millimeter: false,
            accuracy: 0,
            dataFix: {
              preFix: "",
              auFix: "",
            },
          },
          chartDisplayName: "数值",
        },
        fieldName: "value",
        fieldDisplayName: "value",
        fieldType: "DECIMAL",
      },
    ],
    constant: {
      data: [{ value: 12480 }],
      originalData: [{ value: 12480 }],
      fieldList: [
        {
          fieldName: "value",
          fieldDisplayName: "value",
          fieldType: "DECIMAL",
        },
      ],
    },
    form: {
      formPermType: "All",
      formUuid: "",
      formName: "",
    },
    sourceType: "constant",
    api: {
      headers: [],
      processFunction: "function handleResponse (response) { return response }",
      requestBody: "",
      requestParam: [],
      fieldList: [],
      apiUuid: "",
    },
    polling: 3,
  },
  style: {
    position: "absolute",
    left: 400,
    top: 400,
    width: 320,
    height: 104,
    zIndex: 1,
    backgroundColor: "rgba(12,31,48,0.9)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(71,215,232,0.32)",
    borderRadius: 4,
    overflow: "hidden",
  },
  rotate: 0,
  opacity: 1,
  globalConfig: {
    flexDirection: "column",
    alignItems: "flex-start",
    space: 4,
    padding: {
      top: 12,
      right: 16,
      bottom: 12,
      left: 16,
    },
    useFlexGap: true,
  },
  titleName: "",
  titleVisible: true,
  titleOverflow: "ellipsis",
  titleStyle: {
    fontFamily: STANDARD_FONT_FAMILY,
    fontSize: 14,
    color: "rgba(255,255,255,0.72)",
    fontStyle: "normal",
    fontWeight: "normal",
    letterSpacing: 0,
    lineHeight: 1.4,
  },
  prefix: false,
  prefixTitle: "",
  prefixStyle: {
    display: "flex",
    height: "100%",
    fontFamily: STANDARD_FONT_FAMILY,
    fontSize: 14,
    fontStyle: "normal",
    alignSelf: "center",
    color: "rgba(255,255,255,0.78)",
    fontWeight: "normal",
    letterSpacing: 0,
    lineHeight: 1,
  },
  isFollowPrefix: false,
  numberStyle: {
    display: "flex",
    fontFamily: STANDARD_FONT_FAMILY,
    fontSize: 40,
    color: "#47D7E8",
    fontStyle: "normal",
    fontWeight: "bold",
    letterSpacing: 0,
    lineHeight: 1,
  },
  suffix: false,
  suffixTitle: "",
  suffixStyle: {
    display: "flex",
    height: "100%",
    fontFamily: STANDARD_FONT_FAMILY,
    fontSize: 14,
    alignSelf: "center",
    color: "rgba(255,255,255,0.78)",
    fontStyle: "normal",
    fontWeight: "normal",
    letterSpacing: 0,
    lineHeight: 1,
  },
  isFollowSuffix: false,
  decimal: 0,
  separation: true,
  emptyText: "--",
  hasBackground: false,
  numBackground: {
    width: 32,
    height: 48,
    isBgColor: true,
    bgColor: "rgba(71,215,232,0.14)",
    bgImg: "",
  },
  animation: true,
  animateType: 1,
  duration: 1.2,
  entryAnimiation: {
    isShow: false,
    type: "",
  },
  eventConfigures: [],
};
