import type { JsonObject } from "../../types/component.js";

const STANDARD_FONT_FAMILY =
  '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif';

export const indicatorDefaultProps: JsonObject = {
  componentName: "Indicator",
  name: "翻牌器",
  textValue: 1234,
  chartData: {
    isPolling: false,
    indicator: [
      {
        fieldDataConfig: {
          calculateType: "SUM",
          format: {
            numberFormat: "numerical",
            Millimeter: false,
            accuracy: 0,
            dataFix: {
              preFix: "",
              auFix: "",
            },
          },
          chartDisplayName: "数值",
        },
        fieldName: "value",
        fieldDisplayName: "value",
        fieldType: "DECIMAL",
      },
    ],
    constant: {
      data: [{ value: 1234 }],
      originalData: [{ value: 1234 }],
      fieldList: [
        {
          fieldName: "value",
          fieldDisplayName: "value",
          fieldType: "DECIMAL",
        },
      ],
    },
    form: {
      formPermType: "All",
      formUuid: "",
      formName: "",
    },
    sourceType: "constant",
    api: {
      headers: [],
      processFunction: "function handleResponse (response) { return response }",
      requestBody: "",
      requestParam: [],
      fieldList: [],
      apiUuid: "",
    },
    polling: 3,
  },
  style: {
    position: "absolute",
    left: 400,
    top: 400,
    width: 320,
    height: 80,
    zIndex: 1,
    backgroundColor: "rgba(17,61,110,0.68)",
  },
  rotate: 0,
  opacity: 1,
  globalConfig: {
    flexDirection: "column",
    alignItems: "center",
    space: 4,
  },
  titleName: "",
  titleVisible: true,
  titleStyle: {
    fontFamily: STANDARD_FONT_FAMILY,
    fontSize: 18,
    color: "#fff",
    fontStyle: "normal",
    fontWeight: "normal",
    letterSpacing: 1,
    lineHeight: 1,
  },
  prefix: false,
  prefixTitle: "",
  prefixStyle: {
    display: "flex",
    height: "100%",
    fontFamily: STANDARD_FONT_FAMILY,
    fontSize: 18,
    fontStyle: "normal",
    alignSelf: "center",
    color: "#fff",
    fontWeight: "normal",
    letterSpacing: 1,
    lineHeight: 1,
  },
  isFollowPrefix: false,
  numberStyle: {
    display: "flex",
    fontFamily: STANDARD_FONT_FAMILY,
    fontSize: 48,
    color: "#00E5FF",
    fontStyle: "normal",
    fontWeight: "bold",
    letterSpacing: 1,
    lineHeight: 1,
  },
  suffix: false,
  suffixTitle: "",
  suffixStyle: {
    display: "flex",
    height: "100%",
    fontFamily: STANDARD_FONT_FAMILY,
    fontSize: 18,
    alignSelf: "center",
    color: "#fff",
    fontStyle: "normal",
    fontWeight: "normal",
    letterSpacing: 1,
    lineHeight: 1,
  },
  isFollowSuffix: false,
  decimal: 0,
  separation: false,
  hasBackground: false,
  numBackground: {
    width: 36,
    height: 54,
    isBgColor: true,
    bgColor: "rgba(0,229,255,0.15)",
    bgImg: "",
  },
  animation: true,
  animateType: 1,
  duration: 2,
  entryAnimiation: {
    isShow: false,
    type: "",
  },
  eventConfigures: [],
};
