import type { JsonObject } from "../../types/component.js";

export const tabMenuDefaultProps: JsonObject = {
  componentName: "TabMenu",
  name: "Tab列表",
  title: "Tab列表",
  rotate: 0,
  opacity: 1,
  fillContainer: true,
  flexDirection: "row",
  alignType: "center",
  itemAlign: "center",
  textOverflow: "ellipsis",
  cardSpace: 8,
  showIcon: false,
  iconSize: 16,
  iconSpace: 6,
  expandIconSize: 12,
  expandIconColor: "#94a3b8",
  menuData: {
    originType: "static",
    tableMapData: {
      name: "name",
      icon: "icon",
      id: "id",
    },
    selectTabId: "1",
    originalData: [
      {
        name: "总览",
        icon: "",
        id: "1",
      },
      {
        name: "趋势",
        icon: "",
        id: "2",
      },
      {
        name: "分析",
        icon: "",
        id: "3",
      },
      {
        name: "明细",
        icon: "",
        id: "4",
      },
    ],
  },
  menuDefaultStyle: {
    borderType: "solid",
    backgroundColor: "rgba(15, 23, 42, 0.48)",
    backgroundImage: "",
    borderColor: "rgba(148, 163, 184, 0.18)",
    color: "#cbd5e1",
    textAlign: "center",
    letterSpacing: 0,
    fontStyle: "normal",
    fontFamily: "Microsoft YaHei",
    borderRadius: 4,
    borderWidth: 1,
    iconColor: "#94a3b8",
    fontSize: 14,
    lineHeight: 1.4,
    fontWeight: "normal",
    backgroundFillType: "color",
  },
  menuHoverStyle: {
    borderType: "solid",
    backgroundColor: "rgba(56, 189, 248, 0.1)",
    backgroundImage: "",
    borderColor: "rgba(56, 189, 248, 0.38)",
    color: "#f8fafc",
    textAlign: "center",
    letterSpacing: 0,
    fontStyle: "normal",
    fontFamily: "Microsoft YaHei",
    borderRadius: 4,
    borderWidth: 1,
    iconColor: "#7dd3fc",
    fontSize: 14,
    lineHeight: 1.4,
    fontWeight: "normal",
    backgroundFillType: "color",
  },
  menuSelectStyle: {
    borderType: "solid",
    backgroundColor: "rgba(14, 165, 233, 0.2)",
    borderColor: "#38bdf8",
    color: "#f8fafc",
    textAlign: "center",
    backgroundImage: "",
    letterSpacing: 0,
    fontStyle: "normal",
    backgroundFillType: "color",
    fontFamily: "Microsoft YaHei",
    borderRadius: 4,
    borderWidth: 1,
    iconColor: "#7dd3fc",
    fontSize: 14,
    lineHeight: 1.4,
    fontWeight: "bold",
  },
  eventConfigures: [],
  style: {
    rotate: 0,
    top: 96,
    left: 320,
    width: 640,
    position: "absolute",
    opacity: 1,
    height: 48,
    zIndex: 10,
  },
  entryAnimiation: {
    type: "",
    isShow: false,
  },
};
