import type { JsonObject } from "../../types/component.js";

export const tabMenuDefaultProps: JsonObject = {
  componentName: "TabMenu",
  name: "Tab列表",
  title: "Tab列表",
  rotate: 0,
  opacity: 1,
  fillContainer: true,
  flexDirection: "row",
  alignType: "center",
  cardSpace: 6,
  showIcon: false,
  iconSize: 16,
  iconSpace: 6,
  expandIconSize: 12,
  expandIconColor: "rgba(227,240,255,1)",
  menuData: {
    originType: "static",
    tableMapData: {
      name: "name",
      icon: "icon",
      id: "id",
    },
    selectTabId: "1",
    originalData: [
      {
        name: "驾驶舱",
        icon: "group1/M00/03/FE/wKgBCWP8EeiAHj9rAAAGMWTcl1g322.svg",
        id: "1",
      },
      {
        name: "安全看板",
        icon: "group1/M00/03/FE/wKgBCWP8EeiAHj9rAAAGMWTcl1g322.svg",
        id: "2",
      },
      {
        name: "质量看板",
        icon: "group1/M00/03/FE/wKgBCWP8EeiAHj9rAAAGMWTcl1g322.svg",
        id: "3",
      },
      {
        name: "进度看板",
        icon: "group1/M00/03/FE/wKgBCWP8EeiAHj9rAAAGMWTcl1g322.svg",
        id: "4",
      },
      {
        name: "劳务看板",
        icon: "group1/M00/03/FE/wKgBCWP8EeiAHj9rAAAGMWTcl1g322.svg",
        id: "5",
      },
    ],
  },
  menuDefaultStyle: {
    borderType: "solid",
    backgroundColor: "rgba(181,210,252,1)",
    borderColor: "rgba(0,0,0,0)",
    color: "#fff",
    textAlign: "flex-start",
    letterSpacing: 2,
    fontStyle: "italic",
    fontFamily: "优设标题圆",
    borderRadius: 4,
    borderWidth: 0,
    iconColor: "rgba(222,232,255,1)",
    fontSize: 23,
    lineHeight: 2,
    fontWeight: "normal",
    backgroundFillType: "color",
  },
  menuHoverStyle: {
    borderType: "solid",
    backgroundColor: "rgba(181,210,252,1)",
    borderColor: "rgba(0,0,0,0)",
    color: "rgb(205,237,250)",
    textAlign: "flex-start",
    letterSpacing: 2,
    fontStyle: "italic",
    fontFamily: "优设标题圆",
    borderRadius: 4,
    borderWidth: 0,
    iconColor: "rgba(222,232,255,1)",
    fontSize: 23,
    lineHeight: 2,
    fontWeight: "normal",
    backgroundFillType: "color",
  },
  menuSelectStyle: {
    borderType: "solid",
    backgroundColor: "rgba(124,179,237,1)",
    borderColor: "rgba(0,0,0,0)",
    color: "linear-gradient(180deg, rgb(174,255,255) 0%, rgb(255,255,255) 100%)",
    textAlign: "flex-start",
    backgroundImage: "",
    letterSpacing: 2,
    fontStyle: "italic",
    backgroundFillType: "color",
    fontFamily: "优设标题圆",
    borderRadius: 4,
    borderWidth: 0,
    iconColor: "rgba(255,255,255,1)",
    fontSize: 26,
    lineHeight: 2,
    fontWeight: "normal",
  },
  eventConfigures: [],
  style: {
    rotate: 0,
    top: 136.14285714285717,
    left: 356.2857142857142,
    width: 782.2857142857142,
    position: "absolute",
    opacity: 1,
    height: 46.57142857142857,
    zIndex: 501,
  },
  entryAnimiation: {
    type: "",
    isShow: false,
  },
};
