import type { JsonObject } from "../../types/component.js";

export const earth3dDefaultProps: JsonObject = {
  componentName: "Earth3D",
  name: "3D地球",
  title: "3D地球",
  style: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 1000,
    height: 800,
    fontFamily:
      '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
    fontSize: 18,
    color: "#fff",
    textAlign: "center",
    fontStyle: "normal",
    fontWeight: "normal",
    letterSpacing: 1,
    lineHeight: 2,
    zIndex: 1,
  },
  texture: {
    type: "light",
    customUrl: "",
    cloudShow: true,
    cloudSpeed: 0.6,
    cloudOpacity: 0.49,
    cloudDirection: "ccw",
  },
  rotate: 0,
  opacity: 1,
  entryAnimiation: {
    isShow: false,
    type: "",
    destroyAnimation: false,
  },
  longitude: 116.4074,
  latitude: 39.9042,
  cameraDistance: 10,
  earthRadius: 400,
  starBg: {
    show: true,
    autoRotate: true,
    speed: 1,
    direction: "clockwise",
  },
  outAtmosphere: {
    show: true,
    color: "rgba(13,183,248,1)",
    opacity: 0.13,
    speed: 1,
    direction: "clockwise",
  },
  glow: {
    open: true,
    color: "#d07a36",
    strength: 175,
    opacity: 100,
  },
  backLight: {
    open: true,
    color: "rgba(61,183,248,1)",
    opacity: 0.64,
  },
  stroke: {
    open: true,
    outline: true,
    outlineColor: "#DDE9EE",
    lineColor: "#DDE9EE",
    outlineSpeed: 50,
  },
  ambientLight: {
    show: true,
    color: "#ffffff",
    intensity: 2,
  },
  shuttle: {
    isShow: true,
    destroyAnimation: false,
    trigger: ["code"],
    longitude: 116.4074,
    latitude: 39.9042,
    startZoom: 1600,
    endZoom: 800,
    duration: 1000,
  },
  backgroundImage: {
    type: "custom",
  },
  eventConfigures: [],
};
