import type { JsonObject } from "../../types/component.js";

export const lineChartDefaultProps: JsonObject = {
  componentName: "LineChart",
  rotate: 0,
  chartData: {
    isPolling: false,
    indicator: [
      {
        fieldDataConfig: {
          calculateType: "SUM",
          format: {
            numberFormat: "numerical",
            Millimeter: false,
            accuracy: 2,
            dataFix: {
              preFix: "",
              auFix: "",
            },
          },
          chartDisplayName: "value",
        },
        fieldName: "value",
        fieldDisplayName: "value",
        fieldType: "DECIMAL",
      },
    ],
    constant: {
      data: [
        { name: "类目1", type: "系列", value: 101 },
        { name: "类目2", type: "系列", value: 71 },
        { name: "类目3", type: "系列", value: 121 },
        { name: "类目4", type: "系列", value: 95 },
        { name: "类目5", type: "系列", value: 141 },
        { name: "类目6", type: "系列", value: 96 },
      ],
      originalData: [
        { name: "类目1", type: "系列", value: 101 },
        { name: "类目2", type: "系列", value: 71 },
        { name: "类目3", type: "系列", value: 121 },
        { name: "类目4", type: "系列", value: 95 },
        { name: "类目5", type: "系列", value: 141 },
        { name: "类目6", type: "系列", value: 96 },
      ],
      fieldList: [
        { fieldName: "name", fieldDisplayName: "name", fieldType: "LONGTEXT" },
        { fieldName: "type", fieldDisplayName: "type", fieldType: "LONGTEXT" },
        { fieldName: "value", fieldDisplayName: "value", fieldType: "DECIMAL" },
      ],
    },
    form: {
      formPermType: "All",
      formUuid: "",
      formName: "",
    },
    sourceType: "constant",
    api: {
      headers: [],
      processFunction: "function handleResponse (response) { return response }",
      requestBody: "",
      requestParam: [],
      fieldList: [],
      apiUuid: "",
    },
    polling: 3,
    dimension: [
      {
        fieldDataConfig: {
          calculateType: "COUNT",
          chartDisplayName: "name",
        },
        fieldName: "name",
        fieldDisplayName: "name",
        fieldType: "LONGTEXT",
      },
    ],
  },
  eventConfigures: [],
  advanced: true,
  entryAnimiation: {
    type: "",
    isShow: false,
  },
  name: "Line Chart",
  style: {
    top: 72,
    left: 669,
    width: 400,
    position: "absolute",
    height: 226,
    zIndex: 500,
  },
  opacity: 1,
  option: {
    backgroundColor: "transparent",
    color: [
      "#5470c6",
      "#fac858",
      "#ee6666",
      "#73c0de",
      "#3ba272",
      "#fc8452",
      "#9a60b4",
      "#ea7ccc",
    ],
    animiation: {
      show: false,
      type: "",
    },
    tooltip: {
      trigger: "axis",
      show: true,
      backgroundColor: "rgba(3,16,31,0.92)",
      borderColor: "rgba(0,229,255,0.35)",
      borderWidth: 1,
      textStyle: {
        color: "#fff",
        fontWeight: "normal",
        fontSize: 14,
        fontStyle: "normal",
        fontFamily: "serif",
      },
    },
    grid: {
      left: 30,
      top: 60,
      bottom: 42,
      right: 40,
    },
    legend: {
      show: true,
      left: "center",
      top: "top",
      orient: "horizontal",
      itemWidth: 18,
      itemHeight: 12,
      textStyle: {
        color: "#ffffff",
        fontSize: 14,
        fontWeight: "normal",
        fontFamily: "serif",
        fontStyle: "normal",
      },
      icon: "emptyCircle",
    },
    xAxis: {
      type: "category",
      show: true,
      name: "",
      axisTick: {
        show: true,
        inside: true,
        length: 2,
        lineStyle: {
          width: 2,
          type: "dotted",
          color: "#fff",
        },
      },
      axisLine: {
        show: true,
        inside: false,
        lineStyle: {
          color: "#fff",
          width: 1,
          type: "solid",
        },
      },
      splitLine: {
        show: false,
        lineStyle: {
          color: "#0696f9",
          width: 3,
          type: "solid",
        },
      },
      axisLabel: {
        show: true,
        inside: false,
        rotate: 0,
        color: "#e6f7ff",
        fontWeight: "normal",
        fontFamily: "serif",
        fontSize: 12,
        fontStyle: "normal",
        align: "center",
        margin: 8,
      },
    },
    yAxis: {
      type: "value",
      show: true,
      name: "",
      axisTick: {
        show: false,
        inside: true,
        length: 10,
        lineStyle: {
          width: 3,
          type: "solid",
          color: "#fff",
        },
      },
      axisLine: {
        show: false,
        inside: false,
        lineStyle: {
          color: "#0696f9",
          width: 3,
          type: "solid",
        },
      },
      splitLine: {
        show: true,
        lineStyle: {
          width: 1,
          type: "dashed",
          color: "#878C93",
        },
      },
      axisLabel: {
        show: true,
        inside: false,
        rotate: 0,
        color: "#e6f7ff",
        fontWeight: "normal",
        fontFamily: "serif",
        fontStyle: "normal",
        align: "center",
        formatter: "{value}",
        fontSize: 14,
        margin: 8,
      },
    },
    series: [
      {
        __seriesType: "__default",
        symbolSize: 0,
        symbol: "emptyCircle",
        showSymbol: false,
        name: "",
        mapName: "",
        type: "line",
        itemStyle: {
          color: "",
          borderWidth: 2,
          borderColor: "#666666",
          borderType: "solid",
          shadowBlur: 0,
          shadowColor: "#fff",
        },
        label: {
          show: false,
          position: "top",
          fontWeight: "bold",
          color: "#ffffff",
          fontSize: 12,
          fontStyle: "normal",
          fontFamily: "serif",
          rotate: 0,
        },
        lineStyle: {
          width: 3,
        },
      },
    ],
  },
};
