import type { JsonObject } from "../../types/component.js";

export const lineChartDefaultProps: JsonObject = {
  componentName: "LineChart",
  rotate: 0,
  chartData: {
    isPolling: false,
    indicator: [
      {
        fieldDataConfig: {
          calculateType: "SUM",
          format: {
            numberFormat: "numerical",
            Millimeter: false,
            accuracy: 2,
            dataFix: {
              preFix: "",
              auFix: "",
            },
          },
          chartDisplayName: "value",
        },
        fieldName: "value",
        fieldDisplayName: "value",
        fieldType: "DECIMAL",
      },
    ],
    constant: {
      data: [
        { name: "类目1", type: "系列", value: 101 },
        { name: "类目2", type: "系列", value: 71 },
        { name: "类目3", type: "系列", value: 121 },
        { name: "类目4", type: "系列", value: 95 },
        { name: "类目5", type: "系列", value: 141 },
        { name: "类目6", type: "系列", value: 96 },
      ],
      originalData: [
        { name: "类目1", type: "系列", value: 101 },
        { name: "类目2", type: "系列", value: 71 },
        { name: "类目3", type: "系列", value: 121 },
        { name: "类目4", type: "系列", value: 95 },
        { name: "类目5", type: "系列", value: 141 },
        { name: "类目6", type: "系列", value: 96 },
      ],
      fieldList: [
        { fieldName: "name", fieldDisplayName: "name", fieldType: "LONGTEXT" },
        { fieldName: "type", fieldDisplayName: "type", fieldType: "LONGTEXT" },
        { fieldName: "value", fieldDisplayName: "value", fieldType: "DECIMAL" },
      ],
    },
    form: {
      formPermType: "All",
      formUuid: "",
      formName: "",
    },
    sourceType: "constant",
    api: {
      headers: [],
      processFunction: "function handleResponse (response) { return response }",
      requestBody: "",
      requestParam: [],
      fieldList: [],
      apiUuid: "",
    },
    polling: 3,
    dimension: [
      {
        fieldDataConfig: {
          calculateType: "COUNT",
          chartDisplayName: "name",
        },
        fieldName: "name",
        fieldDisplayName: "name",
        fieldType: "LONGTEXT",
      },
    ],
  },
  eventConfigures: [],
  advanced: true,
  entryAnimiation: {
    type: "",
    isShow: false,
  },
  name: "折线图",
  style: {
    top: 72,
    left: 669,
    width: 400,
    position: "absolute",
    height: 226,
    zIndex: 500,
  },
  opacity: 1,
  option: {
    backgroundColor: "transparent",
    color: [
      "#38bdf8",
      "#fbbf24",
      "#fb7185",
      "#34d399",
      "#a78bfa",
      "#f97316",
      "#2dd4bf",
      "#e879f9",
    ],
    animiation: {
      show: false,
      type: "",
    },
    tooltip: {
      trigger: "axis",
      show: true,
      confine: true,
      backgroundColor: "rgba(15, 23, 42, 0.94)",
      borderWidth: 0,
      padding: [8, 10],
      textStyle: {
        color: "#f8fafc",
        fontWeight: "normal",
        fontSize: 14,
        fontStyle: "normal",
        fontFamily: "sans-serif",
      },
      axisPointer: {
        type: "line",
        snap: true,
        lineStyle: {
          color: "rgba(148, 163, 184, 0.6)",
          width: 1,
          type: "dashed",
        },
        label: {
          show: false,
        },
      },
    },
    grid: {
      left: 16,
      right: 16,
      top: 40,
      bottom: 16,
      containLabel: true,
    },
    legend: {
      show: true,
      left: "center",
      top: "top",
      orient: "horizontal",
      type: "scroll",
      itemWidth: 14,
      itemHeight: 8,
      itemGap: 16,
      textStyle: {
        color: "#e2e8f0",
        fontSize: 12,
        fontWeight: "normal",
        fontFamily: "sans-serif",
        fontStyle: "normal",
      },
      icon: "roundRect",
    },
    xAxis: {
      type: "category",
      show: true,
      name: "",
      boundaryGap: false,
      nameGap: 16,
      nameTextStyle: {
        color: "#cbd5e1",
        fontSize: 12,
        fontFamily: "sans-serif",
      },
      axisTick: {
        show: false,
        inside: true,
        length: 2,
        lineStyle: {
          width: 1,
          type: "solid",
          color: "#94a3b8",
        },
      },
      axisLine: {
        show: true,
        inside: false,
        lineStyle: {
          color: "rgba(148, 163, 184, 0.52)",
          width: 1,
          type: "solid",
        },
      },
      splitLine: {
        show: false,
        lineStyle: {
          color: "#0696f9",
          width: 3,
          type: "solid",
        },
      },
      axisLabel: {
        show: true,
        inside: false,
        rotate: 0,
        color: "#cbd5e1",
        fontWeight: "normal",
        fontFamily: "sans-serif",
        fontSize: 12,
        fontStyle: "normal",
        align: "center",
        margin: 10,
        hideOverlap: true,
        overflow: "truncate",
        width: 72,
      },
    },
    yAxis: {
      type: "value",
      show: true,
      name: "",
      position: "left",
      scale: false,
      nameTextStyle: {
        color: "#cbd5e1",
        fontSize: 12,
        fontFamily: "sans-serif",
        padding: [0, 0, 8, 0],
      },
      axisTick: {
        show: false,
        inside: true,
        length: 10,
        lineStyle: {
          width: 3,
          type: "solid",
          color: "#fff",
        },
      },
      axisLine: {
        show: false,
        inside: false,
        lineStyle: {
          color: "#0696f9",
          width: 3,
          type: "solid",
        },
      },
      splitLine: {
        show: true,
        lineStyle: {
          width: 1,
          type: "dashed",
          color: "rgba(148, 163, 184, 0.18)",
        },
      },
      axisLabel: {
        show: true,
        inside: false,
        rotate: 0,
        color: "#cbd5e1",
        fontWeight: "normal",
        fontFamily: "sans-serif",
        fontStyle: "normal",
        align: "center",
        formatter: "{value}",
        fontSize: 14,
        margin: 8,
        hideOverlap: true,
      },
    },
    series: [
      {
        __seriesType: "__default",
        symbolSize: 8,
        symbol: "emptyCircle",
        showSymbol: false,
        name: "",
        mapName: "",
        type: "line",
        itemStyle: {
          borderWidth: 2,
          borderType: "solid",
          shadowBlur: 0,
          shadowColor: "transparent",
        },
        label: {
          show: false,
          position: "top",
          fontWeight: "normal",
          color: "#f8fafc",
          fontSize: 10,
          fontStyle: "normal",
          fontFamily: "sans-serif",
          rotate: 0,
        },
        lineStyle: {
          width: 2,
          type: "solid",
          shadowBlur: 0,
          shadowColor: "rgba(16,175,255,0)",
        },
        connectNulls: false,
        sampling: "none",
        step: false,
        emphasis: {
          focus: "series",
          lineStyle: {
            width: 3,
          },
        },
      },
    ],
  },
};
