import type { JsonObject } from "../../types/component.js";

export const radarChartDefaultProps: JsonObject = {
  componentName: "RadarChart",
  name: "雷达图",
  rotate: 0,
  opacity: 1,
  style: {
    position: "absolute",
    left: 80,
    top: 160,
    width: 520,
    height: 320,
    zIndex: 1,
    backgroundColor: "transparent",
  },
  entryAnimiation: {
    isShow: false,
    type: "",
  },
  margin: {
    top: 50,
    left: 50,
    bottom: 50,
    right: 120,
  },
  min: 0,
  max: 20,
  datasource: {
    sourceType: "constant",
    fieldMode: "multiple",
    autoRefresh: false,
    fieldMappings: [
      {
        key: "series",
        mapFields: [{ path: "s", label: "s", deleted: false }],
      },
      {
        key: "value",
        mapFields: [{ path: "y", label: "y", deleted: false }],
      },
      {
        key: "dimension",
        mapFields: [{ path: "x", label: "x", deleted: false }],
      },
    ],
    constantData: [
      { s: "系列一", x: "维度一", y: 12 },
      { s: "系列一", x: "维度二", y: 14 },
      { s: "系列一", x: "维度三", y: 8 },
      { s: "系列二", x: "维度一", y: 16 },
      { s: "系列二", x: "维度二", y: 10 },
      { s: "系列二", x: "维度三", y: 18 },
    ],
  },
  legendConf: {
    show: true,
    position: {
      top: "top",
      left: "right",
    },
    orient: "vertical",
    icon: "circle",
    font: {
      fontFamily: "Microsoft YaHei",
      fontSize: 12,
      color: "#ffffff",
      fontWeight: "normal",
      fontStyle: "normal",
    },
  },
  axisConf: {
    show: true,
    centerX: 0.5,
    centerY: 0.5,
    radius: 0.35,
    shape: "polygon",
    axisLineColor: "rgba(255,255,255,0.3)",
    axisLineWidth: 1,
    splitLineShow: true,
    splitLineColor: "rgba(255,255,255,0.12)",
    splitLineWidth: 1,
    splitLineType: "solid",
    splitAreaShow: true,
    splitAreaColor: ["rgba(0,0,0,0)", "rgba(255,255,255,0.05)"],
  },
  labelConf: {
    show: true,
    color: "#ffffff",
    fontSize: 12,
    fontFamily: "Microsoft YaHei",
    fontWeight: "normal",
    fontStyle: "normal",
    distance: 12,
  },
  tickConf: {
    show: true,
    count: 5,
    color: "rgba(255,255,255,0.5)",
    fontSize: 10,
    fontFamily: "Microsoft YaHei",
    fontWeight: "normal",
    fontStyle: "normal",
  },
  seriesConf: [
    {
      matchName: "系列一",
      lineColor: "#00E5FF",
      fillColor: "rgba(0,229,255,0.2)",
      lineWidth: 2,
      symbol: "circle",
      symbolSize: 4,
      areaFill: true,
    },
    {
      matchName: "系列二",
      lineColor: "#FFB300",
      fillColor: "rgba(255,179,0,0.2)",
      lineWidth: 2,
      symbol: "circle",
      symbolSize: 4,
      areaFill: true,
    },
  ],
  tooltipConf: {
    show: true,
    backgroundColor: "rgba(3,16,31,0.92)",
    fontFamily: "Microsoft YaHei",
    fontSize: 14,
    color: "#ffffff",
    fontWeight: "normal",
    fontStyle: "normal",
  },
  valueLabelConf: {
    show: true,
    color: "#ffffff",
    fontSize: 11,
    fontFamily: "Microsoft YaHei",
    fontWeight: "normal",
    fontStyle: "normal",
  },
  eventConfigures: [],
};
