import type { JsonObject } from "../../types/component.js";

export const heatMapDefaultProps: JsonObject = {
  componentName: "HeatMap",
  name: "热力图",
  rotate: 0,
  opacity: 1,
  style: {
    position: "absolute",
    left: 60,
    top: 80,
    width: 450,
    height: 250,
    zIndex: 100,
  },
  entryAnimiation: {
    type: "",
    isShow: false,
  },
  marginConf: {
    top: 20,
    left: 45,
    bottom: 15,
    right: 20,
  },
  datasource: {
    sourceType: "constant",
    fieldMode: "multiple",
    constantDataType: "table",
    constantTableColumns: [
      { type: "string", key: "x" },
      { type: "string", key: "y" },
      { type: "number", key: "value" },
    ],
    fieldMappings: [
      { key: "x", mapFields: [{ path: "x", label: "x", deleted: false }] },
      { key: "y", mapFields: [{ path: "y", label: "y", deleted: false }] },
      { key: "value", mapFields: [{ path: "value", label: "value", deleted: false }] },
    ],
    constantData: [
      { x: "12a", y: "Saturday", value: 5 },
      { x: "1a", y: "Saturday", value: 1 },
      { x: "2a", y: "Saturday", value: 0 },
      { x: "3a", y: "Saturday", value: 0 },
      { x: "4a", y: "Saturday", value: 0 },
      { x: "12a", y: "Friday", value: 9 },
      { x: "1a", y: "Friday", value: 3 },
      { x: "2a", y: "Friday", value: 5 },
      { x: "3a", y: "Friday", value: 7 },
      { x: "4a", y: "Friday", value: 2 },
      { x: "12a", y: "Thursday", value: 8 },
      { x: "1a", y: "Thursday", value: 6 },
      { x: "2a", y: "Thursday", value: 4 },
      { x: "3a", y: "Thursday", value: 3 },
      { x: "4a", y: "Thursday", value: 1 },
      { x: "12a", y: "Wednesday", value: 4 },
      { x: "1a", y: "Wednesday", value: 7 },
      { x: "2a", y: "Wednesday", value: 9 },
      { x: "3a", y: "Wednesday", value: 2 },
      { x: "4a", y: "Wednesday", value: 6 },
    ],
  },
  XAxisConf: {
    show: true,
    position: "bottom",
    name: "",
    nameTextStyle: {
      color: "#e6f7ff",
      fontSize: 12,
      fontWeight: "normal",
      fontStyle: "normal",
      fontFamily: "serif",
    },
    axisLine: {
      show: true,
      lineStyle: {
        color: "#ffffff",
        width: 1,
        type: "solid",
      },
    },
    axisTick: {
      show: false,
      inside: false,
      length: 5,
      lineStyle: {
        color: "#ffffff",
        width: 1,
        type: "solid",
      },
    },
    axisLabel: {
      show: true,
      inside: false,
      rotate: 0,
      color: "#e6f7ff",
      fontWeight: "normal",
      fontStyle: "normal",
      fontFamily: "serif",
      fontSize: 12,
      align: "center",
      margin: 8,
    },
    splitLine: {
      show: false,
      lineStyle: {
        color: "#e6f7ff",
        width: 1,
        type: "dashed",
      },
    },
  },
  YAxisConf: {
    show: true,
    position: "left",
    name: "",
    nameTextStyle: {
      color: "#e6f7ff",
      fontSize: 12,
      fontWeight: "normal",
      fontStyle: "normal",
      fontFamily: "serif",
    },
    axisLine: {
      show: true,
      lineStyle: {
        color: "#ffffff",
        width: 1,
        type: "solid",
      },
    },
    axisTick: {
      show: false,
      inside: false,
      length: 5,
      lineStyle: {
        color: "#ffffff",
        width: 1,
        type: "solid",
      },
    },
    axisLabel: {
      show: true,
      inside: false,
      rotate: 0,
      color: "#e6f7ff",
      fontWeight: "normal",
      fontStyle: "normal",
      fontFamily: "serif",
      fontSize: 12,
      align: "center",
      margin: 8,
    },
    splitLine: {
      show: false,
      lineStyle: {
        color: "#e6f7ff",
        width: 1,
        type: "dashed",
      },
    },
  },
  tooltipConf: {
    show: true,
    backgroundColor: "rgba(3,16,31,0.92)",
    color: "#ffffff",
    fontSize: 14,
    padding: 10,
    fontFamily: "Microsoft YaHei",
    fontWeight: "normal",
    fontStyle: "normal",
  },
  visualMappingConf: {
    show: true,
    orient: "vertical",
    left: "right",
    top: "center",
    min: 0,
    max: 10,
    calculable: true,
    realtime: true,
    inverse: false,
    precision: 0,
    itemWidth: 20,
    itemHeight: 140,
    text: ["高", "低"],
    textStyle: {
      color: "#e6f7ff",
      fontSize: 12,
      fontWeight: "normal",
      fontStyle: "normal",
      fontFamily: "serif",
    },
    inRange: {
      color: [
        "#313695",
        "#4575b4",
        "#74add1",
        "#abd9e9",
        "#e0f3f8",
        "#ffffbf",
        "#fee090",
        "#fdae61",
        "#f46d43",
        "#d73027",
        "#a50026",
      ],
    },
  },
  highlightConf: {
    itemStyle: {
      shadowBlur: 10,
      shadowColor: "rgba(0, 0, 0, 0.5)",
      borderColor: "#ffffff",
      borderWidth: 1,
    },
  },
  labelConf: {
    show: false,
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "normal",
    fontStyle: "normal",
    fontFamily: "serif",
    formatter: "{c}",
  },
  eventConfigures: [],
};
