import type { JsonObject } from "../../types/component.js";

export const scrollListDefaultProps: JsonObject = {
  componentName: "ScrollList",
  name: "滚动表格",
  title: "滚动表格",
  rotate: 0,
  opacity: 1,
  style: {
    position: "absolute",
    left: 400,
    top: 400,
    width: 397,
    height: 234,
    zIndex: 1,
    backgroundColor: "#232630",
  },
  entryAnimiation: {
    isShow: false,
    type: "",
  },
  datasource: {
    sourceType: "constant",
    fieldMode: "multiple",
    constantDataType: "table",
    constantTableColumns: [
      { type: "string", key: "region" },
      { type: "number", key: "rate" },
      { type: "string", key: "status" },
    ],
    fieldMappings: [
      {
        key: "columns",
        mapFields: [
          { path: "region", deleted: false, label: "地区" },
          { path: "rate", deleted: false, label: "完成率" },
          { path: "status", deleted: false, label: "完成情况" },
        ],
      },
    ],
    constantData: [
      { _id: "row_1", region: "北京", rate: 87.2, status: "超预期" },
      { _id: "row_2", region: "上海", rate: 80.5, status: "达标" },
      { _id: "row_3", region: "杭州", rate: 72.3, status: "达标" },
      { _id: "row_4", region: "重庆", rate: 65.5, status: "未达标" },
      { _id: "row_5", region: "成都", rate: 58.4, status: "未达标" },
      { _id: "row_6", region: "厦门", rate: 52.5, status: "未达标" },
      { _id: "row_7", region: "云南", rate: 41.2, status: "未达标" },
      { _id: "row_8", region: "泉州", rate: 42.2, status: "未达标" },
      { _id: "row_9", region: "三亚", rate: 46.2, status: "未达标" },
      { _id: "row_10", region: "武汉", rate: 47.2, status: "未达标" },
    ],
  },
  rowCount: 5,
  rowMargin: 10,
  animateProps: {
    animate: false,
    animationType: "rowScroll",
    direction: "bottom2Top",
    hoverPause: false,
    interval: 1,
    duration: 2,
    endBehavior: "continue",
    switchType: "flip",
  },
  vScrollbarProps: {
    railThick: 4,
    railColor: "rgba(230, 247, 255, 0.2)",
    railRadius: 0,
    sliderColor: "rgba(230, 247, 255, 0.45)",
    sliderRadius: 0,
    show: false,
  },
  hScrollbarProps: {
    railThick: 4,
    railColor: "rgb(209, 250, 255)",
    railRadius: 0,
    sliderColor: "rgb(22, 236, 250)",
    sliderRadius: 0,
    show: false,
  },
  rowHeader: {
    isShowHeader: true,
    textOverflow: "ellipsis",
    headerHeight: 35,
    headerAlign: "center",
    bgType: "color",
    headerBg: "#232630",
    headerBgImg: "",
    fontFamily:
      '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
    color: "rgba(235, 245, 255, 1)",
    letterSpacing: 1,
    fontSize: 12,
    fontStyle: "normal",
    fontWeight: "bold",
  },
  customRowStyles: [
    {
      bgType: "color",
      bgColor: "rgba(142, 201, 255, 0.1)",
      bgImg: "",
      offsetX: 0,
      borderColor: "#ffffff00",
      borderWidth: 1,
      radius: 0,
    },
    {
      bgType: "color",
      bgColor: "rgba(142, 201, 255, 0.05)",
      bgImg: "",
      offsetX: 0,
      borderColor: "#ffffff00",
      borderWidth: 1,
      radius: 0,
    },
  ],
  highlight: {
    open: false,
    shadowVisible: false,
    shadowColor: "rgba(0, 0, 0, 0.0)",
    offsetX: 0,
    offsetY: 0,
    blur: 0,
    spread: 0,
    bgType: "color",
    bgColor: "rgba(255, 146, 95, 0.96)",
    bgImg: "",
    selectCount: 1,
    fontFamily:
      '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
    color: "rgba(255, 255, 255, 1)",
    letterSpacing: 1,
    fontSize: 12,
    fontStyle: "normal",
    fontWeight: "bolder",
  },
  matchStyles: [],
  orderColumnCfg: {
    show: false,
    startOrder: 1,
    columnTitle: "#",
    widthType: "fixed",
    orderAlign: "center",
    orderColWidth: 60,
    colMargin: 0,
    fontFamily:
      '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
    color: "rgba(255, 255, 255, 1)",
    letterSpacing: 1,
    fontSize: 12,
    fontStyle: "normal",
    fontWeight: "normal",
  },
  orderStyles: [],
  colConfigs: [
    {
      __seriesType: "__default",
      colFieldName: "",
      widthType: "flex",
      colWidth: 1,
      colMargin: 0,
      showBorder: false,
      borderColor: "rgba(0, 0, 0, 1)",
      borderWidth: 1,
      borderRadius: 10,
      offsetX: 0,
      offsetY: 0,
      bgType: "color",
      colAlign: "center",
      contentType: "text",
      textOverflow: "ellipsis",
      bgImg: "",
      picWidth: 20,
      picHeight: 20,
      actualWidth: 0,
      fontFamily:
        '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
      color: "rgba(255, 255, 255, 1)",
      letterSpacing: 1,
      fontSize: 12,
      fontStyle: "normal",
      fontWeight: "normal",
    },
  ],
  eventConfigures: [],
};
