import type { JsonObject } from "../../types/component.js";

export const pictorialBarChartDefaultProps: JsonObject = {
  componentName: "PictorialBarChart",
  name: "象形柱图",
  rotate: 0,
  opacity: 1,
  style: {
    position: "absolute",
    top: 100,
    left: 100,
    width: 450,
    height: 250,
    zIndex: 91,
    backgroundColor: "transparent",
  },
  entryAnimiation: {
    isShow: false,
    type: "",
  },
  eventConfigures: [],
  globalConf: {
    fontFamily:
      '-apple-system, "Noto Sans", "Helvetica Neue", Helvetica, "Nimbus Sans L", Arial, "Liberation Sans", "PingFang SC", "Hiragino Sans GB", "Noto Sans CJK SC", "Source Han Sans SC", "Source Han Sans CN", "Microsoft YaHei", "Wenquanyi Micro Hei", "WenQuanYi Zen Hei", "ST Heiti", SimHei, "WenQuanYi Zen Hei Sharp", sans-serif',
    animation: true,
    animationType: true,
    animationDuration: 800,
    margin: {
      top: 40,
      bottom: 60,
      left: 50,
      right: 10,
    },
    barConf: {
      innerMargin: -0.5,
      outerMargin: 0,
      overlap: 1,
      svgPath: "M66,0 C66,85.625 88,135.625 132,150 L0,150 C45.3894737,135 67.3894737,85 66,0 Z",
      svgWidth: 1,
      svgHeight: 1,
      barBackgroundColor: "rgba(244,58,46,0.1)",
      repeat: true,
    },
    labelConf: {
      show: true,
      fontSize: 10,
      fontColor: "rgba(255,255,255,1)",
      offsetY: -10,
      precision: 0,
    },
  },
  XAxisConf: {
    show: true,
    name: "",
    nameOffset: 8,
    nameColor: "rgba(255,255,255,1)",
    nameFontSize: 8,
    axisLabelConf: {
      show: true,
      inside: false,
      rotate: 0,
      fontColor: "rgba(255,255,255,1)",
      fontSize: 10,
    },
    axisTickConf: {
      show: false,
      inside: false,
      length: 2,
      width: 1,
      lineType: "solid",
      color: "rgba(255,255,255,1)",
      splitNumber: 4,
    },
    axisLineConf: {
      show: true,
      width: 1,
      lineType: "solid",
      color: "rgba(255,255,255,1)",
    },
    splitLineConf: {
      show: false,
      width: 1,
      lineType: "dashed",
      color: "rgba(255,255,255,0.1)",
    },
  },
  YAxisConf: {
    show: true,
    name: "单位",
    nameOffset: 8,
    nameColor: "rgba(255,255,255,1)",
    nameFontSize: 10,
    axisLabelConf: {
      show: true,
      inside: false,
      rotate: 0,
      fontColor: "rgba(255,255,255,1)",
      fontSize: 8,
    },
    axisTickConf: {
      show: true,
      inside: true,
      length: 4,
      width: 0.5,
      lineType: "solid",
      color: "rgba(255,255,255,1)",
      splitNumber: 4,
    },
    axisLineConf: {
      show: true,
      width: 1,
      lineType: "solid",
      color: "rgba(255,255,255,1)",
    },
    splitLineConf: {
      show: true,
      width: 1,
      lineType: "dashed",
      color: "rgba(230,247,255,0.25)",
    },
  },
  legendConf: {
    show: false,
    orient: "horizontal",
    icon: "rect",
    iconWidth: 10,
    iconHeight: 10,
    precision: 0,
    fontSize: 10,
    fontColor: "rgba(255,255,255,1)",
    position: {
      top: "bottom",
      left: "center",
    },
  },
  guideLineConf: {
    show: false,
    valueType: "max",
    customValue: 0,
    lineColor: "rgba(244,58,46,1)",
    lineType: "dashed",
    showText: false,
    textName: "最大值",
    textColor: "rgba(244,58,46,1)",
    textSize: 12,
  },
  seriesConfs: [
    {
      __seriesType: "__default",
      matchName: "",
      fillColor: "linear-gradient(90deg, rgba(6,80,239,0.4) 0%, rgba(1,207,248,0.7) 100%)",
      suffix: "",
      suffixColor: "rgba(230,247,255,1)",
      suffixSize: 12,
      iconImg: "",
      iconWidth: 10,
      iconHeight: 10,
      iconOffsetY: 0,
      borderColor: "rgba(30,231,231,1)",
      borderWidth: 1.5,
    },
  ],
  datasource: {
    sourceType: "constant",
    fieldMode: "multiple",
    autoRefresh: false,
    fieldMappings: [
      {
        key: "series",
        mapFields: [
          {
            path: "s",
            deleted: false,
            label: "s",
          },
        ],
      },
      {
        key: "value",
        mapFields: [
          {
            path: "y",
            deleted: false,
            label: "y",
          },
        ],
      },
      {
        key: "type",
        mapFields: [
          {
            path: "x",
            deleted: false,
            label: "x",
          },
        ],
      },
    ],
    constantData: [
      {
        s: 1,
        x: "系列一",
        y: "120.2",
      },
      {
        s: 1,
        x: "系列二",
        y: 195,
      },
      {
        s: 1,
        x: "系列三",
        y: 60,
      },
      {
        s: 1,
        x: "系列四",
        y: 96,
      },
      {
        s: 1,
        x: "系列五",
        y: 163,
      },
    ],
  },
};
