import type { JsonObject } from "../../types/component.js";

export const ringChartDefaultProps: JsonObject = {
  componentName: "RingChart",
  rotate: 0,
  chartData: {
    isPolling: false,
    indicator: [
      {
        fieldDataConfig: {
          calculateType: "SUM",
          format: {
            numberFormat: "numerical",
            Millimeter: false,
            accuracy: 2,
            dataFix: {
              preFix: "",
              auFix: "",
            },
          },
          chartDisplayName: "value",
        },
        fieldName: "value",
        fieldDisplayName: "value",
        fieldType: "DECIMAL",
      },
    ],
    constant: {
      data: [
        { name: "类目1", type: "系列", value: 101 },
        { name: "类目2", type: "系列", value: 71 },
        { name: "类目3", type: "系列", value: 121 },
        { name: "类目4", type: "系列", value: 95 },
        { name: "类目5", type: "系列", value: 141 },
        { name: "类目6", type: "系列", value: 96 },
      ],
      originalData: [
        { name: "类目1", type: "系列", value: 101 },
        { name: "类目2", type: "系列", value: 71 },
        { name: "类目3", type: "系列", value: 121 },
        { name: "类目4", type: "系列", value: 95 },
        { name: "类目5", type: "系列", value: 141 },
        { name: "类目6", type: "系列", value: 96 },
      ],
      fieldList: [
        {
          fieldName: "name",
          fieldDisplayName: "name",
          fieldType: "LONGTEXT",
        },
        {
          fieldName: "type",
          fieldDisplayName: "type",
          fieldType: "LONGTEXT",
        },
        {
          fieldName: "value",
          fieldDisplayName: "value",
          fieldType: "DECIMAL",
        },
      ],
    },
    form: {
      formPermType: "All",
      formUuid: "",
      formName: "",
    },
    sourceType: "constant",
    api: {
      headers: [],
      processFunction: "function handleResponse (response) { return response }",
      requestBody: "",
      requestParam: [],
      fieldList: [],
      apiUuid: "",
    },
    polling: 3,
    dimension: [
      {
        fieldDataConfig: {
          calculateType: "COUNT",
          chartDisplayName: "name",
        },
        fieldName: "name",
        fieldDisplayName: "name",
        fieldType: "LONGTEXT",
      },
    ],
  },
  eventConfigures: [],
  advanced: true,
  entryAnimiation: {
    type: "",
    isShow: false,
  },
  name: "环形图",
  style: {
    top: 72,
    left: 669,
    width: 400,
    position: "absolute",
    height: 226,
    zIndex: 500,
  },
  opacity: 1,
  option: {
    backgroundColor: "transparent",
    title: {
      show: false,
      text: "",
      left: "center",
      top: "center",
      padding: 0,
      textStyle: {
        color: "#F8FAFC",
        fontSize: 18,
        fontFamily: "Microsoft YaHei",
        fontWeight: "normal",
        align: "center",
      },
    },
    color: [
      "#5B8FF9",
      "#5AD8A6",
      "#5D7092",
      "#F6BD16",
      "#E8684A",
      "#6DC8EC",
      "#9270CA",
      "#FF9D4D",
    ],
    animiation: {
      show: false,
      type: "",
    },
    legend: {
      show: true,
      type: "scroll",
      left: "center",
      top: 8,
      width: "96%",
      orient: "horizontal",
      offsetX: 0,
      offsetY: 0,
      icon: "circle",
      itemWidth: 10,
      itemHeight: 10,
      itemGap: 16,
      selectedMode: false,
      textStyle: {
        fontFamily: "Microsoft YaHei",
        color: "#CBD5E1",
        fontSize: 12,
        fontStyle: "normal",
        fontWeight: "normal",
        width: 72,
        overflow: "truncate",
        ellipsis: "...",
      },
    },
    series: [
      {
        hoverAnimation: false,
        left: 0,
        center: ["50%", "58%"],
        name: "",
        mapName: "",
        startAngle: 90,
        clockwise: true,
        avoidLabelOverlap: true,
        minShowLabelAngle: 4,
        percentPrecision: 1,
        stillShowZeroSum: false,
        showEmptyCircle: true,
        emptyCircleStyle: {
          color: "rgba(148, 163, 184, 0.16)",
          borderColor: "rgba(148, 163, 184, 0.32)",
          borderWidth: 1,
        },
        emphasis: {
          label: {
            show: true,
          },
          scale: true,
          scaleSize: 6,
          itemStyle: {
            opacity: 1,
            shadowBlur: 12,
            shadowOffsetX: 0,
            shadowColor: "rgba(15, 23, 42, 0.36)",
          },
        },
        itemStyle: {
          borderType: "solid",
          borderColor: "rgba(15, 23, 42, 0.85)",
          borderRadius: 4,
          shadowBlur: 0,
          borderWidth: 2,
          shadowColor: "rgba(15, 23, 42, 0.24)",
        },
        label: {
          formatter: "{b}\n{d}%",
          content: "namePercent",
          fontFamily: "Microsoft YaHei",
          color: "#F8FAFC",
          show: false,
          fontSize: 14,
          position: "center",
          fontStyle: "normal",
          fontWeight: "normal",
        },
        labelLine: {
          length2: 14,
          show: false,
          length: 10,
          smooth: true,
        },
        type: "pie",
        radius: ["38%", "66%"],
      },
    ],
    tooltip: {
      show: true,
      trigger: "item",
      confine: true,
      backgroundColor: "rgba(15, 23, 42, 0.94)",
      borderColor: "rgba(148, 163, 184, 0.28)",
      borderWidth: 1,
      padding: [8, 12],
      textStyle: {
        fontFamily: "Microsoft YaHei",
        color: "#F8FAFC",
        fontSize: 13,
        fontStyle: "normal",
        fontWeight: "normal",
      },
    },
  },
  decorator: {
    innerRing: {
      isActive: false,
      innerRadius: 0.2,
      outerRadius: 0.23,
      opacity: 0.5,
      animateSpeed: 0.8,
      animateDirection: "clockwise",
    },
    outerRing: {
      isActive: false,
      arcWidth: 0.15,
      opacity: 0.2,
    },
  },
  rotatingAnimation: {
    isActive: false,
    height: 6,
    opacity: 1,
    duration: 5,
    selectMode: "none",
    isHover: false,
  },
  borderGap: 0,
  ringText: {
    isActive: false,
    fontSize: 14,
    fontFamily: "Microsoft YaHei",
    fontWeight: "normal",
    color: "#F8FAFC",
    distance: 10,
  },
};
