import type { JsonObject } from "../../types/component.js";

export const stackBarChartDefaultProps: JsonObject = {
  componentName: "StackBarChart",
  rotate: 0,
  chartData: {
    isPolling: false,
    indicator: [
      {
        fieldDataConfig: {
          calculateType: "SUM",
          format: {
            numberFormat: "numerical",
            Millimeter: false,
            accuracy: 2,
            dataFix: {
              preFix: "",
              auFix: "",
            },
          },
          chartDisplayName: "value",
        },
        fieldName: "value",
        fieldDisplayName: "value",
        fieldType: "DECIMAL",
      },
    ],
    constant: {
      data: [
        { name: "类目1", type: "系列1", value: 120 },
        { name: "类目1", type: "系列2", value: 80 },
        { name: "类目2", type: "系列1", value: 90 },
        { name: "类目2", type: "系列2", value: 110 },
        { name: "类目3", type: "系列1", value: 150 },
        { name: "类目3", type: "系列2", value: 70 },
        { name: "类目4", type: "系列1", value: 60 },
        { name: "类目4", type: "系列2", value: 130 },
      ],
      originalData: [
        { name: "类目1", type: "系列1", value: 120 },
        { name: "类目1", type: "系列2", value: 80 },
        { name: "类目2", type: "系列1", value: 90 },
        { name: "类目2", type: "系列2", value: 110 },
        { name: "类目3", type: "系列1", value: 150 },
        { name: "类目3", type: "系列2", value: 70 },
        { name: "类目4", type: "系列1", value: 60 },
        { name: "类目4", type: "系列2", value: 130 },
      ],
      fieldList: [
        { fieldName: "name", fieldDisplayName: "name", fieldType: "LONGTEXT" },
        { fieldName: "type", fieldDisplayName: "type", fieldType: "LONGTEXT" },
        { fieldName: "value", fieldDisplayName: "value", fieldType: "DECIMAL" },
      ],
    },
    form: {
      formPermType: "All",
      formUuid: "",
      formName: "",
    },
    sourceType: "constant",
    api: {
      headers: [],
      processFunction: "function handleResponse (response) { return response }",
      requestBody: "",
      requestParam: [],
      fieldList: [],
      apiUuid: "",
    },
    polling: 3,
    dimension: [
      {
        fieldDataConfig: {
          calculateType: "COUNT",
          chartDisplayName: "name",
        },
        fieldName: "name",
        fieldDisplayName: "name",
        fieldType: "LONGTEXT",
      },
      {
        fieldDataConfig: {
          calculateType: "COUNT",
          chartDisplayName: "type",
        },
        fieldName: "type",
        fieldDisplayName: "type",
        fieldType: "LONGTEXT",
      },
    ],
  },
  eventConfigures: [],
  advanced: true,
  entryAnimiation: {
    type: "",
    isShow: false,
  },
  name: "堆叠柱状图",
  style: {
    top: 72,
    left: 669,
    width: 400,
    position: "absolute",
    height: 226,
    zIndex: 500,
  },
  opacity: 1,
  option: {
    backgroundColor: "transparent",
    color: [
      "#5B8FF9",
      "#5AD8A6",
      "#F6BD16",
      "#E8684A",
      "#6DC8EC",
      "#9270CA",
      "#FF9D4D",
      "#5D7092",
    ],
    barStyle: {
      gradient: false,
      gradientDarken: 0.12,
    },
    animiation: {
      show: false,
      type: "",
    },
    tooltip: {
      trigger: "axis",
      show: true,
      backgroundColor: "rgba(15, 23, 42, 0.94)",
      borderColor: "rgba(148, 163, 184, 0.35)",
      borderWidth: 1,
      padding: [8, 10],
      textStyle: {
        color: "#F8FAFC",
        fontWeight: "normal",
        fontSize: 12,
        fontStyle: "normal",
        fontFamily: "sans-serif",
      },
      axisPointer: {
        type: "shadow",
        label: {
          show: false,
        },
      },
    },
    grid: {
      left: 16,
      top: 40,
      bottom: 16,
      right: 16,
      containLabel: true,
    },
    legend: {
      show: true,
      left: "center",
      top: "top",
      orient: "horizontal",
      itemWidth: 12,
      itemHeight: 8,
      itemGap: 16,
      textStyle: {
        color: "#CBD5E1",
        fontSize: 12,
        fontWeight: "normal",
        fontFamily: "sans-serif",
        fontStyle: "normal",
      },
      icon: "roundRect",
    },
    xAxis: {
      type: "category",
      show: true,
      name: "",
      axisTick: {
        show: false,
        inside: false,
        length: 2,
        lineStyle: {
          width: 2,
          type: "solid",
          color: "#64748B",
        },
      },
      axisLine: {
        show: true,
        inside: false,
        lineStyle: {
          color: "#64748B",
          width: 1,
          type: "solid",
        },
      },
      splitLine: {
        show: false,
        lineStyle: {
          color: "rgba(148, 163, 184, 0.16)",
          width: 1,
          type: "solid",
        },
      },
      axisLabel: {
        show: true,
        inside: false,
        rotate: 0,
        color: "#CBD5E1",
        fontWeight: "normal",
        fontFamily: "sans-serif",
        fontSize: 12,
        fontStyle: "normal",
        align: "center",
        margin: 8,
        hideOverlap: true,
        width: 72,
        overflow: "truncate",
        ellipsis: "...",
      },
    },
    yAxis: {
      type: "value",
      show: true,
      name: "",
      position: "left",
      axisTick: {
        show: false,
        inside: true,
        length: 10,
        lineStyle: {
          width: 3,
          type: "solid",
          color: "#fff",
        },
      },
      axisLine: {
        show: false,
        inside: false,
        lineStyle: {
          color: "#64748B",
          width: 1,
          type: "solid",
        },
      },
      splitLine: {
        show: true,
        lineStyle: {
          width: 1,
          type: "dashed",
          color: "rgba(148, 163, 184, 0.22)",
        },
      },
      axisLabel: {
        show: true,
        inside: false,
        rotate: 0,
        color: "#CBD5E1",
        fontWeight: "normal",
        fontFamily: "sans-serif",
        fontStyle: "normal",
        align: "center",
        formatter: "{value}",
        fontSize: 12,
        margin: 8,
      },
    },
    series: [
      {
        __seriesType: "__default",
        name: "",
        mapName: "",
        type: "bar",
        barWidth: 18,
        barMinWidth: 6,
        barMaxWidth: 32,
        barMinHeight: 0,
        stack: "__stackBar",
        stackStrategy: "samesign",
        barCategoryGap: "20%",
        itemStyle: {
          borderWidth: 0,
          borderColor: "rgba(255, 255, 255, 0.18)",
          borderType: "solid",
          shadowBlur: 0,
          shadowColor: "rgba(15, 23, 42, 0.28)",
          borderRadius: 2,
        },
        label: {
          show: false,
          position: "inside",
          fontWeight: "normal",
          color: "#F8FAFC",
          fontSize: 12,
          fontStyle: "normal",
          fontFamily: "sans-serif",
          rotate: 0,
          formatter: "{c}",
        },
        labelLayout: {
          hideOverlap: true,
        },
        emphasis: {
          focus: "series",
        },
      },
    ],
  },
};
